### ISSUE TITLE
EP Error D:\a\_work\1\s\onnxruntime\core\session\provider_bridge_ort.cc:1131 onnxruntime::ProviderLibrary::Get [ONNXRuntimeError]

### ISSUE THREAD

**Issue by waaaok** [aigc-apps/sd-webui-EasyPhoto#100]
![image](https://github.com/aigc-apps/sd-webui-EasyPhoto/assets/144203874/34020a58-dcf8-47b9-9491-9280b3183786)
为了用GPU计算，我输入了两个命令:
pip uninstall onnxruntime
pip install onnxruntime-gpu
仍然报错显示默认用cpu
另外我的电脑里并没D盘，这个报错的文件目录是什么D:\a\_work\1\s\onnxruntime\core\session\provider_bridge_ort.

**Comment by yunkchen** [comment]
你默认python环境是你启动webui的python环境么？
可能有多个Python环境的，一台电脑里

**Comment by bubbliiiing** [comment]
这个魔塔的模型只支持CPU哈，为了兼容性，并不是onnxruntime的问题

**Comment by waaaok** [comment]
1.我没有D盘，所有这个D盘路径我没看懂
2.我的python环境是webui的环境
