### ISSUE TITLE
What is the difference between Easyphoto and kohya?

### ISSUE THREAD

**Issue by Amazon90** [aigc-apps/sd-webui-EasyPhoto#102]
Is it another tool for Lora training?
If you want to swap face, you only need one image to use sd-roop and sd-reactor.
If you use 5-10 images, you can use kohya to train Lora model, so what are the advantages of using easyphoto?

**Comment by yunkchen** [comment]
Welcome to try EasyPhoto and compare the result with  sd-roop/sd-reactor.
Otherways, you could also try to train a LoRA by kohya.
I believe you would find the answer at the end.

**Comment by wuziheng** [comment]
Thanks for this question：
Our project is dedicated to using stablediffusion technology to create more realistic and visually appealing image editing techniques. Initially, we focused on portrait editing, and Lora is a part of the technology we've been working on. We have put significant effort into refining this aspect of the technology, but it also encompasses a wide range of other AI algorithms and techniques that come together to produce the final result. We appreciate your ongoing interest.

CN：我们的项目致力于使用stablediffusion技术打造更逼真，美观的图像编辑技术，人像是我们最初选择的方向，Lora是我们涉及的一部分技术，我们着重打磨了这部分技术，但也还包括大量的其他AI算法和技术，共同呈现最后的效果，欢迎您的持续关注。
