### ISSUE TITLE
多卡训练时报错

### ISSUE THREAD

**Issue by West2022** [aigc-apps/sd-webui-EasyPhoto#112]
train_file_path :  /workspace/extensions/sd-webui-EasyPhoto/scripts/train_kohya/train_lora.py
cache_log_file_path   :  /workspace/extensions/sd-webui-EasyPhoto/train_kohya_log.txt
2023-09-21 16:05:39.712810: I tensorflow/core/util/port.cc:110] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2023-09-21 16:05:39.754387: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 AVX512F AVX512_VNNI FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
The following values were not passed to `accelerate launch` and had defaults used instead:
	`--num_processes` was set to a value of `4`
		More than one GPU was found, enabling multi-GPU training.
		If this was unintended please pass in `--num_processes=1`.
	`--num_machines` was set to a value of `1`
	`--dynamo_backend` was set to a value of `'no'`
To avoid this warning pass in values for each of the problematic parameters or run `accelerate config`.
2023-09-21 16:05:46.548276: I tensorflow/core/util/port.cc:110] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2023-09-21 16:05:46.548998: I tensorflow/core/util/port.cc:110] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2023-09-21 16:05:46.556482: I tensorflow/core/util/port.cc:110] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2023-09-21 16:05:46.586803: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 AVX512F AVX512_VNNI FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2023-09-21 16:05:46.587251: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 AVX512F AVX512_VNNI FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2023-09-21 16:05:46.594740: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 AVX512F AVX512_VNNI FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2023-09-21 16:05:46.643670: I tensorflow/core/util/port.cc:110] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2023-09-21 16:05:46.682157: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 AVX512F AVX512_VNNI FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2023-09-21 16:05:51,560 - modelscope - INFO - PyTorch version 2.0.1+cu118 Found.
2023-09-21 16:05:51,564 - modelscope - INFO - PyTorch version 2.0.1+cu118 Found.
2023-09-21 16:05:51,565 - modelscope - INFO - TensorFlow version 2.13.0 Found.
2023-09-21 16:05:51,565 - modelscope - INFO - Loading ast index from /root/.cache/modelscope/ast_indexer
2023-09-21 16:05:51,569 - modelscope - INFO - TensorFlow version 2.13.0 Found.
2023-09-21 16:05:51,569 - modelscope - INFO - Loading ast index from /root/.cache/modelscope/ast_indexer
2023-09-21 16:05:51,596 - modelscope - INFO - Loading done! Current index file version is 1.7.1, with md5 b611efdf0e8371e9f336016e02c8d398 and a total number of 861 components indexed
2023-09-21 16:05:51,599 - modelscope - INFO - Loading done! Current index file version is 1.7.1, with md5 b611efdf0e8371e9f336016e02c8d398 and a total number of 861 components indexed
2023-09-21 16:05:51,702 - modelscope - INFO - PyTorch version 2.0.1+cu118 Found.
2023-09-21 16:05:51,707 - modelscope - INFO - TensorFlow version 2.13.0 Found.
2023-09-21 16:05:51,707 - modelscope - INFO - Loading ast index from /root/.cache/modelscope/ast_indexer
2023-09-21 16:05:51,739 - modelscope - INFO - Loading done! Current index file version is 1.7.1, with md5 b611efdf0e8371e9f336016e02c8d398 and a total number of 861 components indexed
Namespace(pretrained_model_name_or_path='/workspace/extensions/sd-webui-EasyPhoto/models/stable-diffusion-v1-5', pretrained_model_ckpt='/workspace/models/Stable-diffusion/Chilloutmix-Ni-pruned-fp16-fix.safetensors', revision=None, dataset_name=None, dataset_config_name=None, train_data_dir='/workspace/outputs/easyphoto-user-id-infos/sx/processed_images', image_column='image', caption_column='text', validation=True, validation_prompt='easyphoto_face, easyphoto, 1person', num_validation_images=4, validation_epochs=1, validation_steps=100, neg_prompt='sketch, low quality, worst quality, low quality shadow, lowres, inaccurate eyes, huge eyes, longbody, bad anatomy, cropped, worst face, strange mouth, bad anatomy, inaccurate limb, bad composition, ugly, noface, disfigured, duplicate, ugly, text, logo', guidance_scale=9, max_train_samples=None, output_dir='/workspace/outputs/easyphoto-user-id-infos/sx/user_weights', cache_dir=None, seed=42, resolution=512, center_crop=False, random_flip=True, train_batch_size=1, num_train_epochs=100, max_train_steps=800, gradient_accumulation_steps=1, gradient_checkpointing=False, learning_rate=0.0001, scale_lr=False, lr_scheduler='constant', lr_warmup_steps=0, train_text_encoder=True, snr_gamma=None, use_8bit_adam=False, allow_tf32=False, dataloader_num_workers=16, adam_beta1=0.9, adam_beta2=0.999, adam_weight_decay=0.01, adam_epsilon=1e-08, max_grad_norm=1.0, hub_token=None, prediction_type=None, hub_model_id=None, logging_dir='/workspace/outputs/easyphoto-user-id-infos/sx/user_weights', mixed_precision='fp16', report_to='tensorboard', local_rank=3, save_state=False, checkpointing_steps=100, checkpoints_total_limit=None, resume_from_checkpoint=None, enable_xformers_memory_efficient_attention=True, noise_offset=0, rank=128, network_alpha=64, template_dir='/workspace/extensions/sd-webui-EasyPhoto/models/training_templates', template_mask=True, template_mask_dir=None, mask_post_url=None, merge_best_lora_based_face_id=True, merge_best_lora_name='sx', cache_log_file='/workspace/extensions/sd-webui-EasyPhoto/train_kohya_log.txt', faceid_post_url=None)
Namespace(pretrained_model_name_or_path='/workspace/extensions/sd-webui-EasyPhoto/models/stable-diffusion-v1-5', pretrained_model_ckpt='/workspace/models/Stable-diffusion/Chilloutmix-Ni-pruned-fp16-fix.safetensors', revision=None, dataset_name=None, dataset_config_name=None, train_data_dir='/workspace/outputs/easyphoto-user-id-infos/sx/processed_images', image_column='image', caption_column='text', validation=True, validation_prompt='easyphoto_face, easyphoto, 1person', num_validation_images=4, validation_epochs=1, validation_steps=100, neg_prompt='sketch, low quality, worst quality, low quality shadow, lowres, inaccurate eyes, huge eyes, longbody, bad anatomy, cropped, worst face, strange mouth, bad anatomy, inaccurate limb, bad composition, ugly, noface, disfigured, duplicate, ugly, text, logo', guidance_scale=9, max_train_samples=None, output_dir='/workspace/outputs/easyphoto-user-id-infos/sx/user_weights', cache_dir=None, seed=42, resolution=512, center_crop=False, random_flip=True, train_batch_size=1, num_train_epochs=100, max_train_steps=800, gradient_accumulation_steps=1, gradient_checkpointing=False, learning_rate=0.0001, scale_lr=False, lr_scheduler='constant', lr_warmup_steps=0, train_text_encoder=True, snr_gamma=None, use_8bit_adam=False, allow_tf32=False, dataloader_num_workers=16, adam_beta1=0.9, adam_beta2=0.999, adam_weight_decay=0.01, adam_epsilon=1e-08, max_grad_norm=1.0, hub_token=None, prediction_type=None, hub_model_id=None, logging_dir='/workspace/outputs/easyphoto-user-id-infos/sx/user_weights', mixed_precision='fp16', report_to='tensorboard', local_rank=0, save_state=False, checkpointing_steps=100, checkpoints_total_limit=None, resume_from_checkpoint=None, enable_xformers_memory_efficient_attention=True, noise_offset=0, rank=128, network_alpha=64, template_dir='/workspace/extensions/sd-webui-EasyPhoto/models/training_templates', template_mask=True, template_mask_dir=None, mask_post_url=None, merge_best_lora_based_face_id=True, merge_best_lora_name='sx', cache_log_file='/workspace/extensions/sd-webui-EasyPhoto/train_kohya_log.txt', faceid_post_url=None)
2023-09-21 16:05:51,877 - modelscope - INFO - PyTorch version 2.0.1+cu118 Found.
2023-09-21 16:05:51,882 - modelscope - INFO - TensorFlow version 2.13.0 Found.
2023-09-21 16:05:51,882 - modelscope - INFO - Loading ast index from /root/.cache/modelscope/ast_indexer
2023-09-21 16:05:51,913 - modelscope - INFO - Loading done! Current index file version is 1.7.1, with md5 b611efdf0e8371e9f336016e02c8d398 and a total number of 861 components indexed
Namespace(pretrained_model_name_or_path='/workspace/extensions/sd-webui-EasyPhoto/models/stable-diffusion-v1-5', pretrained_model_ckpt='/workspace/models/Stable-diffusion/Chilloutmix-Ni-pruned-fp16-fix.safetensors', revision=None, dataset_name=None, dataset_config_name=None, train_data_dir='/workspace/outputs/easyphoto-user-id-infos/sx/processed_images', image_column='image', caption_column='text', validation=True, validation_prompt='easyphoto_face, easyphoto, 1person', num_validation_images=4, validation_epochs=1, validation_steps=100, neg_prompt='sketch, low quality, worst quality, low quality shadow, lowres, inaccurate eyes, huge eyes, longbody, bad anatomy, cropped, worst face, strange mouth, bad anatomy, inaccurate limb, bad composition, ugly, noface, disfigured, duplicate, ugly, text, logo', guidance_scale=9, max_train_samples=None, output_dir='/workspace/outputs/easyphoto-user-id-infos/sx/user_weights', cache_dir=None, seed=42, resolution=512, center_crop=False, random_flip=True, train_batch_size=1, num_train_epochs=100, max_train_steps=800, gradient_accumulation_steps=1, gradient_checkpointing=False, learning_rate=0.0001, scale_lr=False, lr_scheduler='constant', lr_warmup_steps=0, train_text_encoder=True, snr_gamma=None, use_8bit_adam=False, allow_tf32=False, dataloader_num_workers=16, adam_beta1=0.9, adam_beta2=0.999, adam_weight_decay=0.01, adam_epsilon=1e-08, max_grad_norm=1.0, hub_token=None, prediction_type=None, hub_model_id=None, logging_dir='/workspace/outputs/easyphoto-user-id-infos/sx/user_weights', mixed_precision='fp16', report_to='tensorboard', local_rank=1, save_state=False, checkpointing_steps=100, checkpoints_total_limit=None, resume_from_checkpoint=None, enable_xformers_memory_efficient_attention=True, noise_offset=0, rank=128, network_alpha=64, template_dir='/workspace/extensions/sd-webui-EasyPhoto/models/training_templates', template_mask=True, template_mask_dir=None, mask_post_url=None, merge_best_lora_based_face_id=True, merge_best_lora_name='sx', cache_log_file='/workspace/extensions/sd-webui-EasyPhoto/train_kohya_log.txt', faceid_post_url=None)
Namespace(pretrained_model_name_or_path='/workspace/extensions/sd-webui-EasyPhoto/models/stable-diffusion-v1-5', pretrained_model_ckpt='/workspace/models/Stable-diffusion/Chilloutmix-Ni-pruned-fp16-fix.safetensors', revision=None, dataset_name=None, dataset_config_name=None, train_data_dir='/workspace/outputs/easyphoto-user-id-infos/sx/processed_images', image_column='image', caption_column='text', validation=True, validation_prompt='easyphoto_face, easyphoto, 1person', num_validation_images=4, validation_epochs=1, validation_steps=100, neg_prompt='sketch, low quality, worst quality, low quality shadow, lowres, inaccurate eyes, huge eyes, longbody, bad anatomy, cropped, worst face, strange mouth, bad anatomy, inaccurate limb, bad composition, ugly, noface, disfigured, duplicate, ugly, text, logo', guidance_scale=9, max_train_samples=None, output_dir='/workspace/outputs/easyphoto-user-id-infos/sx/user_weights', cache_dir=None, seed=42, resolution=512, center_crop=False, random_flip=True, train_batch_size=1, num_train_epochs=100, max_train_steps=800, gradient_accumulation_steps=1, gradient_checkpointing=False, learning_rate=0.0001, scale_lr=False, lr_scheduler='constant', lr_warmup_steps=0, train_text_encoder=True, snr_gamma=None, use_8bit_adam=False, allow_tf32=False, dataloader_num_workers=16, adam_beta1=0.9, adam_beta2=0.999, adam_weight_decay=0.01, adam_epsilon=1e-08, max_grad_norm=1.0, hub_token=None, prediction_type=None, hub_model_id=None, logging_dir='/workspace/outputs/easyphoto-user-id-infos/sx/user_weights', mixed_precision='fp16', report_to='tensorboard', local_rank=2, save_state=False, checkpointing_steps=100, checkpoints_total_limit=None, resume_from_checkpoint=None, enable_xformers_memory_efficient_attention=True, noise_offset=0, rank=128, network_alpha=64, template_dir='/workspace/extensions/sd-webui-EasyPhoto/models/training_templates', template_mask=True, template_mask_dir=None, mask_post_url=None, merge_best_lora_based_face_id=True, merge_best_lora_name='sx', cache_log_file='/workspace/extensions/sd-webui-EasyPhoto/train_kohya_log.txt', faceid_post_url=None)
09/21/2023 16:05:52 - INFO - __main__ - Distributed environment: MULTI_GPU  Backend: nccl
Num processes: 4
Process index: 2
Local process index: 2
Device: cuda:2

Mixed precision type: fp16

09/21/2023 16:05:52 - INFO - __main__ - Distributed environment: MULTI_GPU  Backend: nccl
Num processes: 4
Process index: 3
Local process index: 3
Device: cuda:3

Mixed precision type: fp16

09/21/2023 16:05:52 - INFO - __main__ - Distributed environment: MULTI_GPU  Backend: nccl
Num processes: 4
Process index: 0
Local process index: 0
Device: cuda:0

Mixed precision type: fp16

09/21/2023 16:05:52 - INFO - __main__ - Distributed environment: MULTI_GPU  Backend: nccl
Num processes: 4
Process index: 1
Local process index: 1
Device: cuda:1

Mixed precision type: fp16

{'timestep_spacing', 'sample_max_value', 'clip_sample_range', 'thresholding', 'dynamic_thresholding_ratio', 'prediction_type', 'variance_type'} was not found in config. Values will be initialized to default values.
loading u-net: <All keys matched successfully>
loading u-net: <All keys matched successfully>
loading u-net: <All keys matched successfully>
loading u-net: <All keys matched successfully>
loading vae: <All keys matched successfully>
loading vae: <All keys matched successfully>
loading vae: <All keys matched successfully>
loading vae: <All keys matched successfully>
loading text encoder: <All keys matched successfully>
loading text encoder: <All keys matched successfully>
loading text encoder: <All keys matched successfully>
loading text encoder: <All keys matched successfully>
create LoRA network. base dim (rank): 128, alpha: 64
neuron dropout: p=None, rank dropout: p=None, module dropout: p=None
create LoRA for Text Encoder:
create LoRA network. base dim (rank): 128, alpha: 64
neuron dropout: p=None, rank dropout: p=None, module dropout: p=None
create LoRA for Text Encoder:
create LoRA for Text Encoder: 72 modules.
create LoRA network. base dim (rank): 128, alpha: 64
neuron dropout: p=None, rank dropout: p=None, module dropout: p=None
create LoRA for Text Encoder:
create LoRA for Text Encoder: 72 modules.
create LoRA for Text Encoder: 72 modules.
create LoRA for U-Net: 192 modules.
enable LoRA for text encoder
enable LoRA for U-Net
create LoRA for U-Net: 192 modules.
enable LoRA for text encoder
enable LoRA for U-Net
create LoRA for U-Net: 192 modules.
enable LoRA for text encoder
enable LoRA for U-Net
create LoRA network. base dim (rank): 128, alpha: 64
neuron dropout: p=None, rank dropout: p=None, module dropout: p=None
create LoRA for Text Encoder:
create LoRA for Text Encoder: 72 modules.
Resolving data files: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 31/31 [00:00<00:00, 186013.48it/s]
Downloading data files: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 16/16 [00:00<00:00, 52184.19it/s]
Downloading data files: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 15/15 [00:00<00:00, 53272.28it/s]
Extracting data files: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 15/15 [00:00<00:00, 3402.07it/s]
Generating train split: 15 examples [00:00, 1863.20 examples/s]
Resolving data files: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 31/31 [00:00<00:00, 185747.75it/s]
Resolving data files: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 31/31 [00:00<00:00, 187895.12it/s]
create LoRA for U-Net: 192 modules.
enable LoRA for text encoder
enable LoRA for U-Net
Resolving data files: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 31/31 [00:00<00:00, 138617.72it/s]
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: -7) local_rank: 0 (pid: 9616) of binary: /usr/bin/python
Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.10/dist-packages/accelerate/commands/launch.py", line 989, in <module>
    main()
  File "/usr/local/lib/python3.10/dist-packages/accelerate/commands/launch.py", line 985, in main
    launch_command(args)
  File "/usr/local/lib/python3.10/dist-packages/accelerate/commands/launch.py", line 970, in launch_command
    multi_gpu_launcher(args)
  File "/usr/local/lib/python3.10/dist-packages/accelerate/commands/launch.py", line 646, in multi_gpu_launcher
    distrib_run.run(args)
  File "/usr/local/lib/python3.10/dist-packages/torch/distributed/run.py", line 785, in run
    elastic_launch(
  File "/usr/local/lib/python3.10/dist-packages/torch/distributed/launcher/api.py", line 134, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/usr/local/lib/python3.10/dist-packages/torch/distributed/launcher/api.py", line 250, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
============================================================
/workspace/extensions/sd-webui-EasyPhoto/scripts/train_kohya/train_lora.py FAILED
------------------------------------------------------------
Failures:
[1]:
  time      : 2023-09-21_16:06:13
  host      : ip-10-59-180-158-gz02
  rank      : 1 (local_rank: 1)
  exitcode  : -7 (pid: 9617)
  error_file: <N/A>
  traceback : Signal 7 (SIGBUS) received by PID 9617
[2]:
  time      : 2023-09-21_16:06:13
  host      : ip-10-59-180-158-gz02
  rank      : 2 (local_rank: 2)
  exitcode  : -7 (pid: 9618)
  error_file: <N/A>
  traceback : Signal 7 (SIGBUS) received by PID 9618
[3]:
  time      : 2023-09-21_16:06:13
  host      : ip-10-59-180-158-gz02
  rank      : 3 (local_rank: 3)
  exitcode  : -7 (pid: 9619)
  error_file: <N/A>
  traceback : Signal 7 (SIGBUS) received by PID 9619
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2023-09-21_16:06:13
  host      : ip-10-59-180-158-gz02
  rank      : 0 (local_rank: 0)
  exitcode  : -7 (pid: 9616)
  error_file: <N/A>
  traceback : Signal 7 (SIGBUS) received by PID 9616
============================================================
Error executing the command: Command '['/usr/bin/python', '-m', 'accelerate.commands.launch', '--mixed_precision=fp16', '--main_process_port=3456', '/workspace/extensions/sd-webui-EasyPhoto/scripts/train_kohya/train_lora.py', '--pretrained_model_name_or_path=/workspace/extensions/sd-webui-EasyPhoto/models/stable-diffusion-v1-5', '--pretrained_model_ckpt=/workspace/models/Stable-diffusion/Chilloutmix-Ni-pruned-fp16-fix.safetensors', '--train_data_dir=/workspace/outputs/easyphoto-user-id-infos/sx/processed_images', '--caption_column=text', '--resolution=512', '--random_flip', '--train_batch_size=1', '--gradient_accumulation_steps=1', '--dataloader_num_workers=16', '--max_train_steps=800', '--checkpointing_steps=100', '--learning_rate=0.0001', '--lr_scheduler=constant', '--lr_warmup_steps=0', '--train_text_encoder', '--seed=42', '--rank=128', '--network_alpha=64', '--validation_prompt=easyphoto_face, easyphoto, 1person', '--validation_steps=100', '--output_dir=/workspace/outputs/easyphoto-user-id-infos/sx/user_weights', '--logging_dir=/workspace/outputs/easyphoto-user-id-infos/sx/user_weights', '--enable_xformers_memory_efficient_attention', '--mixed_precision=fp16', '--template_dir=/workspace/extensions/sd-webui-EasyPhoto/models/training_templates', '--template_mask', '--merge_best_lora_based_face_id', '--merge_best_lora_name=sx', '--cache_log_file=/workspace/extensions/sd-webui-EasyPhoto/train_kohya_log.txt', '--validation']' returned non-zero exit status 1.

**Comment by wuziheng** [comment]
当前还不明确支持多卡，官方没有测试多卡，还请等待后续推进，也欢迎验证提交相关改进。
