### ISSUE TITLE
关于LoRA融合

### ISSUE THREAD

**Issue by Albeforia** [aigc-apps/sd-webui-EasyPhoto#115]
作者您好，很棒的工作！我看到您在训练完成后，将“最优”的LoRA进行了merge（即验证图片中和用户图片最相似的对应的LoRA）。这是一个很有意思的想法，我想请教几个问题：
1. 这样做对效果改善大吗？有没有对比过融合和不融合的LoRA效果
2. 这样做不会把没有拟合的LoRA或者过拟合的LoRA合并？（因为这些都是不同训练步长时的权重）

如果我的理解有误还请指正，谢谢！

**Comment by bubbliiiing** [comment]
> 作者您好，很棒的工作！我看到您在训练完成后，将“最优”的LoRA进行了merge（即验证图片中和用户图片最相似的对应的LoRA）。这是一个很有意思的想法，我想请教几个问题：
> 
> 1. 这样做对效果改善大吗？有没有对比过融合和不融合的LoRA效果
> 2. 这样做不会把没有拟合的LoRA或者过拟合的LoRA合并？（因为这些都是不同训练步长时的权重）
> 
> 如果我的理解有误还请指正，谢谢！

1、有一定效果，可以保证lora出图的相似性比较高，毕竟用的都是最像的Lora
2、会，但过拟合有些时候不体现在相似性上，体现在 模糊、躁点、图像崩坏上

**Comment by wuziheng** [comment]
融合lora 出于一个朴素的观察， 把validation 开到10， 在预设800的情况下，你可能会遇到一种情况780/790的效果都还不错，800突然下降比较明显。为了解决这一问题，使得模型可以在自动化的链路中有更稳定可靠的效果，从而引入了这一 验证 融合的流程，效果有部分提升，更重要的是解决了链路的稳定性问题。
