### ISSUE TITLE
Notification: extension schedule to be added to webui extension index

### ISSUE THREAD

**Issue by w-e-w** [aigc-apps/sd-webui-EasyPhoto#116]
we received a request to add this extension to the webui extension index
https://github.com/AUTOMATIC1111/stable-diffusion-webui-extensions/pull/193
this extensional will be add to the index after a week if no objection is raised

if you would like to change the description name or anything about how it's being listed or if you would not like it to be please let us know or make a new PR so you can change the details yourself

**Comment by zouxinyi0625** [comment]
Thanks for the notification. We will keep you informed in case of any changes.

**Comment by wuziheng** [comment]
LGTM
