### ISSUE TITLE
以下问题希望解决

### ISSUE THREAD

**Issue by AlexanderDash** [aigc-apps/sd-webui-EasyPhoto#118]
1.弄出一个停止训练按钮,有时候参数调错了要重启webui太麻烦了
2.我见到模型文件缓存都放在了C盘,可以直接放在秋叶启动器的文件夹中或让用户选择一个文件夹
3.多显卡选择,因为webui启动后有些模型加载没得清理就占显存,而easyphoto插件会使用跟webui同样的显卡进行训练,显存不够用
4.多显卡分布式训练,可能windows不支持NCCL不知道这个能解决不

**Comment by wuziheng** [comment]
1. 当前训练是subprocess调用的，理论上确实可以再call一个system的 call 去kill 我们会跟进这一需求
2. 模型文件缓存 如果是modelscope的模型可以通过启动添加 环境变量更改缓存路径，我们验证后更新到wiki
3. 我们会经常清理显存，多卡对社区用户的环境兼容性影响很大，有在尝试。感谢您的建议。
4. 问题同3

**Comment by wuziheng** [comment]
1.多显卡训练受限于lora的问题，在我们下2个版本升级之前都难以解决
2.关闭训练的讨论类似于 https://github.com/aigc-apps/sd-webui-EasyPhoto/issues/159，我们会讨论是否需要这一功能，但大概率也会归类到saas化 从而不支持

关闭
