### ISSUE TITLE
更新SDXL的lora训练

### ISSUE THREAD

**Issue by AlexanderDash** [aigc-apps/sd-webui-EasyPhoto#120]
xl常用的Controlnet已经完善了
虽然但是,目前用kohya脚本训练xl的lora,batchsize=1,1024*1024,只有22G以上显存的才不会cuda out of memory..............................,
青龙的脚本可以在16G显存以下

**Comment by wuziheng** [comment]
正在做尝试，直接引入sdxl+lora还是效果不太稳定。 我们会渐近式先引入 sdxl 的文到图 生成底图 再走1.5的换脸和ep的后处理，这个链路的效果稳定且已验证，即将上线。

**Comment by wuziheng** [comment]
渐进的这个路线几乎和原定的sdxl+lora差不多了，全图除了face部分都是xl直出，face部分ep的效果还是不错的，所以整体还行，且兼容性问题会小一些. end2end 的xl 我们也在持续试验，未来大概率都要到xl
