### ISSUE TITLE
Crop_face_preprocess 关闭时会在嘴部处理部分报错

### ISSUE THREAD

**Issue by 1605707467qq** [aigc-apps/sd-webui-EasyPhoto#130]
Crop_face_preprocess
关闭Crop_face_preprocess时的图片，(600，800)
![image](https://github.com/aigc-apps/sd-webui-EasyPhoto/assets/69078348/4a630276-b0e9-4fd5-bd37-1b6891cc373d)

![image](https://github.com/aigc-apps/sd-webui-EasyPhoto/assets/69078348/eab8554b-65af-4ae2-8882-179505da136c)开启
(512,682)
![image](https://github.com/aigc-apps/sd-webui-EasyPhoto/assets/69078348/1ff447bf-0950-452e-b3bb-016a778c2c2e)

Crop_face_preprocess时的图片尺寸(600,800)->(536, 666)
![image](https://github.com/aigc-apps/sd-webui-EasyPhoto/assets/69078348/13708ff5-2c0f-4035-ab56-defa55fb0031)

并且会在后面将长宽处理为32的倍数，最小边设置为512后另一边为32的倍数
没开Crop_face_preprocess则不会
![image](https://github.com/aigc-apps/sd-webui-EasyPhoto/assets/69078348/92db3130-4576-400f-87e2-0d64be9f23ef)

关闭时会在处理嘴部报错
![image](https://github.com/aigc-apps/sd-webui-EasyPhoto/assets/69078348/48d7c59b-c998-4b7b-8025-53340092f9cb)

所以尝试在关闭时把嘴部的参数关闭掉，结果：
![image](https://github.com/aigc-apps/sd-webui-EasyPhoto/assets/69078348/6251178c-c236-40f3-b73c-f6bc6c01ff54)

仍然报错……缺少参数，需要提issue了

**Comment by bubbliiiing** [comment]
这个已经修复了，麻烦拉取一下最新的代码

**Comment by 1605707467qq** [comment]
> 这个已经修复了，麻烦拉取一下最新的代码

好！感谢大佬
