### ISSUE TITLE
Illegal instruction after EasyPhoto installation

### ISSUE THREAD

**Issue by longswordinhand** [aigc-apps/sd-webui-EasyPhoto#131]
Hi there
I can run the sd without any question in Ubuntu 22.04. However, after I installed the EasyPhoto extension, it had an error as: 
./webui.sh: line 255: 73876 Illegal instruction     (core dumped) "${python_cmd}" -u "${LAUNCH_SCRIPT}" "$@"
Your help and suggestions are appreciated.

**Comment by yunkchen** [comment]
https://github.com/AUTOMATIC1111/stable-diffusion-webui/issues/4785

**Comment by wuziheng** [comment]
if helpful， we will close this ISSUE in 24hours

**Comment by longswordinhand** [comment]
I tried the solution. The problem still exists. My GPU is old, RTX 2080. Now I am trying using cpu now. thanks.

**Comment by wuziheng** [comment]
You can try a cloud GPU on AliyunDSW or AutoDL， maybe better.

**Comment by longswordinhand** [comment]
Sure, I will follow your suggestions. Please close this issue. Thanks a lot, Ziheng.

**Comment by wuziheng** [comment]
README provide freetiar for Aliyun， can have a try。 CLOSED
