### ISSUE TITLE
[saas化需求]进度的获取方式

### ISSUE THREAD

**Issue by stepkim** [aigc-apps/sd-webui-EasyPhoto#133]
webui上的那个进度, 可以通过api的方式支持一下吗

**Comment by wuziheng** [comment]
你是说下方的log 框里面展示的训练进度么？

**Comment by stepkim** [comment]
是的, 现在只能在webui或者去到gpu服务器的log里面去看进度, 如果需要通过api去获取进度的话暂时好像还不支持

**Comment by stepkim** [comment]
目前关于进度的问题:
1. 多个页面同时发起训练任务的话, 在webui上显示的进度会有错乱的情况(可考虑添加一个获取训练任务进度的接口, 通过任务的userid/taskid去获取指定任务的进度, 如果是通过taskid的话, 训练接口需要添加一个taskid字段)
2. 推理的时候获取进度也不支持(预期是可以通过taskid去获取指定推理的进度)

**Comment by wuziheng** [comment]
sorry，国庆期间，团队休假，节后我们来跟进这些需求，当然如果评估后觉得是足够saas化而不在开源版本实现，也会及时在这个issue下与你沟通。 @stepkim

**Comment by stepkim** [comment]
好的

**Comment by wuziheng** [comment]
@stepkim step 团队讨论后觉得，saas化的需求还是让开源拥护者自行适配，我们在阿里云的相关产品会有一定的支持，但也无法做到根据用户的需求提供saas话需求。我们会优先去跟进和算法效果相关的内容。
