### ISSUE TITLE
训练异常

### ISSUE THREAD

**Issue by Harvi-C** [aigc-apps/sd-webui-EasyPhoto#135]
为什么有时候部署了新的代码，相同参数下，训练出来的 LoRA 模型只有 40 多兆的大小，推理效果大打折扣，正常时应该是 150 兆

**Comment by wuziheng** [comment]
确认一下rank的大小，可以提供一下截图么，最近的版本应该都没有做过相关修改。

**Comment by Harvi-C** [comment]
感谢回复，rank 是 128，network_alpha 是 64，参数用的都是原参数没有改过

**Comment by Harvi-C** [comment]
> 确认一下rank的大小，可以提供一下截图么，最近的版本应该都没有做过相关修改。

感谢回复，rank 是 128，network_alpha 是 64，参数用的都是原参数没有改过

**Comment by wuziheng** [comment]
请check一下你环境的diffusers 版本
是否是0.18.2?

**Comment by bubbliiiing** [comment]
> > 确认一下rank的大小，可以提供一下截图么，最近的版本应该都没有做过相关修改。
> 
> 感谢回复，rank 是 128，network_alpha 是 64，参数用的都是原参数没有改过

应该是因为diffusers版本不同导致lora施加方式的不同，需要固定在0.18.2以下，新版本可能会导致lora加错位置

**Comment by Harvi-C** [comment]
> > > 确认一下rank的大小，可以提供一下截图么，最近的版本应该都没有做过相关修改。
> > 
> > 
> > 感谢回复，rank 是 128，network_alpha 是 64，参数用的都是原参数没有改过
> 
> 应该是因为diffusers版本不同导致lora施加方式的不同，需要固定在0.18.2以下，新版本可能会导致lora加错位置

非常感谢，确实是这个原因导致的，降低 diffusers 的版本后问题解决了
