### ISSUE TITLE
与facechain最大的区别和优势是什么？

### ISSUE THREAD

**Issue by ykk648** [aigc-apps/sd-webui-EasyPhoto#14]
我理解多了一个landmark对齐+openpose controlnet 对inpainting做监督

**Comment by dancemanUK** [comment]
还有对纯windows的环境的兼容性好，毕竟一堆绘画佬，不是人人会python。

**Comment by wuziheng** [comment]
官方回答：
1. 本repo的作者就是facechain[PR104](https://github.com/modelscope/facechain/pull/104)， inpaint功能和lora validate/ensemble的开发者和提供者。
2.这个Repo主要帮助大家快速在SDWebUI的生态下，完成基于Inpaint的艺术照的生成。


个人理解：
1. Facechain 当前的主要路径走的是基于lora和多lora融合的纯生成方案。（at 2023/09/05），原理上来说inpaint路径需要的Lora可能需要更大的参数和更复杂的训练，这个如果细微比对PR104 和我们两边的代码，是能找到差异的。
2. 大家所有用到的预处理是大同小异的，facechain的核心的管理者和我们都是好朋友，我们也是FaceChain功能开发者，大家隶属不同部门，在他们项目开源前也都互通有无过，大家侧重的功能是有一些差异的，正如你看到我们是focus在inpaint路径上的。
3. WebUI生态和我们的的产品生态更相关，我们也更希望在这个生态上帮助不写/少写code的同学，降低准入的门槛。

**Comment by wuziheng** [comment]
欢迎随时交流，我们会对这个ISSUE做一定修改，避免不必要的一些问题。
