### ISSUE TITLE
[check_id_valid] 关于lora文件路径检测

### ISSUE THREAD

**Issue by AlexanderDash** [aigc-apps/sd-webui-EasyPhoto#140]
插件会检测\models\Lora这个文件夹中,是否存在和outputs\easyphoto-user-id-infos这个文件夹中,和lora同名的文件夹,假如我把训练好的lora嵌套一个文件夹,在easyphoto面板它就检测不到id了,

之前我用了副启动器的Easyphoto来训练,我使用了windows自带的命令mklink /j 将主启动器的Lora文件夹的嵌套文件夹映射在副启动器的models文件夹下并命名为Lora确实可以在副启动器的inference找到id,但是在主启动器是找不到id的,看来是需要修改插件相关代码

不嵌套一个文件夹的话,在webui只能在全部lora中找训练好的lora,lora少还好,lora多就很难找,这样会效率降低,且不能分类lora很难受

请告诉我相关代码在哪个文件第几行代码谢谢,我使用vscode搜索不到相关代码的位置呜呜呜

**Comment by wuziheng** [comment]
https://github.com/aigc-apps/sd-webui-EasyPhoto/blob/7feff39c9058ad0e7d0e40cd46a41b279b01bdf7/scripts/easyphoto_utils.py#L19

请参考值这个函数，我们会调用这个来判断id和相关文件是否存在，不知道这个能否帮助你进行自定义的功能拓展。

**Comment by wuziheng** [comment]
如果您后续根据解答已经解决这个问题，我们会在24h 关闭这一issue

**Comment by AlexanderDash** [comment]
我找到这个函数了

**Comment by AlexanderDash** [comment]
> https://github.com/aigc-apps/sd-webui-EasyPhoto/blob/7feff39c9058ad0e7d0e40cd46a41b279b01bdf7/scripts/easyphoto_utils.py#L19
> 
> 请参考值这个函数，我们会调用这个来判断id和相关文件是否存在，不知道这个能否帮助你进行自定义的功能拓展。

from modules.paths import models_path,我见到models path在模块里面,请问这个模块在哪里
