### ISSUE TITLE
AutoDl云端运行webui报错：No matching distribution found for tb-nightly

### ISSUE THREAD

**Issue by sujianfeng-vip** [aigc-apps/sd-webui-EasyPhoto#141]
运行环境：
镜像：aigc-apps/sd-webui-EasyPhoto/sd-webui-EasyPhoto:v2
GPU：RTX A5000(24GB) * 1
CPU：16 vCPU Intel(R) Xeon(R) Platinum 8350C CPU @ 2.60GHz
内存：42GB

运行webui报错信息：
stderr: ERROR: Ignored the following versions that require a different python version: 1.11.0 Requires-Python <3.13,>=3.9; 1.11.0rc1 Requires-Python <3.13,>=3.9; 1.11.0rc2 Requires-Python <3.13,>=3.9; 1.11.1 Requires-Python <3.13,>=3.9; 1.11.2 Requires-Python <3.13,>=3.9; 1.11.3 Requires-Python <3.13,>=3.9
ERROR: Could not find a version that satisfies the requirement tb-nightly (from gfpgan) (from versions: none)
ERROR: No matching distribution found for tb-nightly

**Comment by wuziheng** [comment]
还请您提供一下完整的webui log ，谢谢！

**Comment by wuziheng** [comment]
autodl 请使用这一环境
https://www.codewithgpu.com/i/aigc-apps/sd-webui-EasyPhoto/sd-webui-EasyPhoto

**Comment by hellosa** [comment]
他使用的 aigc-apps/sd-webui-EasyPhoto/sd-webui-EasyPhoto:v2 不就是 https://www.codewithgpu.com/i/aigc-apps/sd-webui-EasyPhoto/sd-webui-EasyPhoto 中的镜像了吗？都是 v2 

我的做法是：
1）把 pip 源给换了，换成百度的就行，或许清华的也行
~/.pip/pip.conf 
[global]
index-url = https://mirror.baidu.com/pypi/simple
[install]
trusted-host=mirror.baidu.com
2）即便如此，也会因为下载的包太多太大，占满了系统盘
我的做法是把 miniconda3 给移动到数据盘，再软链回来系统盘
