### ISSUE TITLE
 Bus error. It is possible that dataloader's workers are out of shared memory. Please try to raise your shared memory limit

### ISSUE THREAD

**Issue by fallbernana123456** [aigc-apps/sd-webui-EasyPhoto#145]
Steps:   0%|▏                                                                                                                                                                   | 1/800 [00:17<3:57:13, 17.81s/it, lr=5e-5, step_loss=0.0114]ERROR: Unexpected bus error encountered in worker. This might be caused by insufficient shared memory (shm).
ERROR: Unexpected bus error encountered in worker. This might be caused by insufficient shared memory (shm).
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/torch/utils/data/dataloader.py", line 1132, in _try_get_data
    data = self._data_queue.get(timeout=timeout)
  File "/usr/lib/python3.10/multiprocessing/queues.py", line 113, in get
    if not self._poll(timeout):
  File "/usr/lib/python3.10/multiprocessing/connection.py", line 257, in poll
    return self._poll(timeout)
  File "/usr/lib/python3.10/multiprocessing/connection.py", line 424, in _poll
    r = wait([self], timeout)
  File "/usr/lib/python3.10/multiprocessing/connection.py", line 931, in wait
    ready = selector.select(timeout)
  File "/usr/lib/python3.10/selectors.py", line 416, in select
    fd_event_list = self._selector.poll(timeout)
  File "/usr/local/lib/python3.10/dist-packages/torch/utils/data/_utils/signal_handling.py", line 66, in handler
    _error_if_any_worker_fails()
RuntimeError: DataLoader worker (pid 1884) is killed by signal: Bus error. It is possible that dataloader's workers are out of shared memory. Please try to raise your shared memory limit.

GPU 16Gx2 . docker安装。这个是指gpu不够吗？最少需要多大的？

**Comment by wuziheng** [comment]
根据您的log，看起来是运行内存不够，导致训练的dataloader的workers 开多了就OOM挂了，我们似乎默认的dataloader的workers 是1。我确认一下，如果是的话，那就是你的内存太小，需要clean一下机器其他的进程和内存。

**Comment by wuziheng** [comment]
![iwEcAqNwbmcDAQTRDigF0QagBrASlBqImpRjwgUVRzJAwKsAB9MAAAAAz7JqQggACaJpbQoAC9IANRxC png_720x720q90](https://github.com/aigc-apps/sd-webui-EasyPhoto/assets/11889926/5d4f1885-7fcc-4524-a437-2692493fbfb4)

dataloader num workers ，这个参数windows 默认是0也就是1， linux开的16， 如果你是linux 可以调小这个数字到2，4 试试

**Comment by wuziheng** [comment]
CPU OOM closed

**Comment by fallbernana123456** [comment]
> ![iwEcAqNwbmcDAQTRDigF0QagBrASlBqImpRjwgUVRzJAwKsAB9MAAAAAz7JqQggACaJpbQoAC9IANRxC png_720x720q90](https://user-images.githubusercontent.com/11889926/273439670-5d4f1885-7fcc-4524-a437-2692493fbfb4.jpg)
> 
> dataloader num workers ，这个参数windows 默认是0也就是1， linux开的16， 如果你是linux 可以调小这个数字到2，4 试试

没有用，我修改为 2 一样报错

**Comment by fallbernana123456** [comment]
> CPU OOM closed

这个指的是什么？
