### ISSUE TITLE
Inference stage image failed to generate

### ISSUE THREAD

**Issue by l-dawei** [aigc-apps/sd-webui-EasyPhoto#146]
Great project, thank you to the author for their excellent work.

The entire training process is completely normal, but during the inference stage, images were not generated (very few can be generated). As I am a remote connected server, every time I perform inference, the server will get stuck and reconnect.

Could you help me? Thanks a lot.

<img width="1280" alt="微信图片_20231008084619" src="https://github.com/aigc-apps/sd-webui-EasyPhoto/assets/56504017/c06896a4-552b-4976-b61a-772dd47efb38">

**Comment by wuziheng** [comment]
please provide your server log， and according to your upload example， there exists alot of possibility such as faceangle too huge make detect miss and so on

**Comment by wuziheng** [comment]
and my suggestion， if you have a 16G GPU memory，try to use SDXL-Beta， to validate the lora performance of your preset userid

**Comment by wuziheng** [comment]
another problem may you upload too huge image

**Comment by l-dawei** [comment]
Thank you for your reply, I have solved the problem.
