### ISSUE TITLE
[aki-4.4 good]urllib3.exceptions.SSLError: [SSL: DECRYPTION_FAILED_OR_BAD_RECORD_MAC] decryption failed or bad record mac (_ssl.c:2578)

### ISSUE THREAD

**Issue by masterliu2021** [aigc-apps/sd-webui-EasyPhoto#149]
![image](https://github.com/aigc-apps/sd-webui-EasyPhoto/assets/95142418/3ff2af3c-5076-4cd1-a65b-4ba9e50dfa1c)
![image](https://github.com/aigc-apps/sd-webui-EasyPhoto/assets/95142418/985192c3-37f5-4694-9424-926f6b55401b)
Upload photos and click to start training
The training progress appears, but the error message in the screenshot above appears immediately.
Then the training was stopped. What is the reason?
Tried again and again and changed photos, but the same thing happened.

**Comment by masterliu2021** [comment]
> ![image](https://user-images.githubusercontent.com/95142418/273449965-3ff2af3c-5076-4cd1-a65b-4ba9e50dfa1c.png) ![image](https://user-images.githubusercontent.com/95142418/273449995-985192c3-37f5-4694-9424-926f6b55401b.png) Upload photos and click to start training The training progress appears, but the error message in the screenshot above appears immediately. Then the training was stopped. What is the reason? Tried again and again and changed photos, but the same thing happened.

Python 3.10.11 (tags/v3.10.11:7d4cc5a, Apr  5 2023, 00:38:17) [MSC v.1929 64 bit (AMD64)]
Version: v1.6.0-125-g59544321
Commit hash: 59544321aa019d71d220b1da1eec703aa44fa8eb
current transparent-background 1.2.4
Installing requirements for easyphoto-webui
Installing requirements for tensorflow
Installing requirements for easyphoto-webui
Installing requirements for modelscope
Installing requirements for easyphoto-webui
Installing requirements for diffusers
Installing requirements for TemporalKit extension
Launching Web UI with arguments: --theme dark --xformers --no-half-vae --disable-nan-check --api --autolaunch
Tag Autocomplete: Could not locate model-keyword extension, Lora trigger word completion will be limited to those added through the extra networks menu.
[-] ADetailer initialized. version: 23.8.0, num models: 9
2023-10-08 20:32:17,462 - modelscope - INFO - PyTorch version 2.0.1+cu118 Found.
2023-10-08 20:32:17,465 - modelscope - INFO - TensorFlow version 2.14.0 Found.
2023-10-08 20:32:17,465 - modelscope - INFO - Loading ast index from C:\Users\Win10\.cache\modelscope\ast_indexer
2023-10-08 20:32:17,532 - modelscope - INFO - Loading done! Current index file version is 1.8.4, with md5 9fbba0fbbf68c3ff682185742ab1b41f and a total number of 902 components indexed
[AddNet] Updating model hashes...
[AddNet] Updating model hashes...
2023-10-08 20:32:19,575 - ControlNet - INFO - ControlNet v1.1.410
ControlNet preprocessor location: D:\soft\AI\sd-webui-aki\sd-webui-aki-v4.2\sd-webui-aki-v4.2\extensions\sd-webui-controlnet\annotator\downloads
2023-10-08 20:32:19,792 - ControlNet - INFO - ControlNet v1.1.410

**Comment by wuziheng** [comment]
1. please try on aki-v4.4， we test easyphoto on aki-v4.4
2. seems network problem, and provide a logger log, which include your upload error jpg

**Comment by masterliu2021** [comment]
> 1. please try on aki-v4.4， we test easyphoto on aki-v4.4
> 2. seems network problem, and provide a logger log, which include your upload error jpg
刚发现您是中文开发者呀，我就用中文回复了
切换版本至秋葉1.6稳定版就可以跑了
感谢回复，祝越来越好

**Comment by wuziheng** [comment]
好的谢谢您的的关注！
