### ISSUE TITLE
[关闭美颜/SDXL支持]更新更多高级选项

### ISSUE THREAD

**Issue by sunbo11112** [aigc-apps/sd-webui-EasyPhoto#153]
预训练包括开启美颜、支持SDXL的LORA训练，控制人物微表情的选项

**Comment by wuziheng** [comment]
1. 开启美颜我们来设置一下
2. 微表情在sdxl-beta模式下比较好添加，其他模式有点依赖模板本身的表情。
3. SDXL训练在做了，但推出与否还是跟随生态的完整度去决策

**Comment by wuziheng** [comment]
1. 美颜功能关闭参考 https://github.com/aigc-apps/sd-webui-EasyPhoto/pull/161
2. sdxl lora 短期不会在人脸上发布，会在anyid分支进行实验性内测，欢迎下载代码一同研究 https://github.com/aigc-apps/sd-webui-EasyPhoto/tree/anyid
3. 微表情已经立项在推进。

**Comment by wuziheng** [comment]
@hkunzhe  人脸LORA的相关测试分支也可以在这里link一下。
