### ISSUE TITLE
希望添加打包可移植选项

### ISSUE THREAD

**Issue by yunwuhai** [aigc-apps/sd-webui-EasyPhoto#154]
目前的插件内似乎并没有合理的可移植选项，即当在A电脑训练出模型后，将Lora模型导入B电脑后，并不能直接使用本插件。希望能有一种比较方便或通用的方式，能够比较快速打包本插件所需的所有数据。

**Comment by yunkchen** [comment]
项目依赖的模型比较多，如果B电脑是个新环境，可以把整个stable-diffusion-webui目录迁移过去；
如果B电脑已经有webui，那可以把A电脑下面extension和models 拷贝过去

**Comment by wuziheng** [comment]
如果你需要的是在两个都部署好可以运行EasyPhoto的环境下迁移某个指定用户的数据例如Lora，参考图片，这个是可以做到的，参考这个函数 https://github.com/aigc-apps/sd-webui-EasyPhoto/blob/9011301f77d73dfe80a1bc3f4e921a1330abd941/scripts/easyphoto_utils.py#L19
如果是希望整体运行环境的迁移，参考@yunkchen的答案。

**Comment by yunwuhai** [comment]
> 如果你需要的是在两个都部署好可以运行EasyPhoto的环境下迁移某个指定用户的数据例如Lora，参考图片，这个是可以做到的，参考这个函数
> 
> https://github.com/aigc-apps/sd-webui-EasyPhoto/blob/9011301f77d73dfe80a1bc3f4e921a1330abd941/scripts/easyphoto_utils.py#L19
> 
> 
> 如果是希望整体运行环境的迁移，参考@yunkchen的答案。

我参考了这个方法，然后将‘outputs/easyphoto-user-id-infos’中的文件打包进行了迁移，同时将‘models\Lora’文件也进行了迁移（直接用'easyphoto-user-id-infos'里面存储的safetensors似乎也是一样的），测试可以使用。

**Comment by yunwuhai** [comment]
https://github.com/aigc-apps/sd-webui-EasyPhoto/issues/154#issuecomment-1754467446

我参考了这个方法，然后将‘outputs/easyphoto-user-id-infos’中的文件打包进行了迁移，同时将‘models\Lora’文件也进行了迁移（直接用'easyphoto-user-id-infos'里面存储的safetensors似乎也是一样的），测试可以使用。

**Comment by yunwuhai** [comment]
https://github.com/aigc-apps/sd-webui-EasyPhoto/issues/154#issuecomment-1754467446

我参考了这个方法，然后将‘outputs/easyphoto-user-id-infos’中的文件打包进行了迁移，同时将‘models\Lora’文件也进行了迁移（直接用'easyphoto-user-id-infos'里面存储的safetensors似乎也是一样的），测试可以使用。
