### ISSUE TITLE
Autodl 配置问题

### ISSUE THREAD

**Issue by VoyageWang** [aigc-apps/sd-webui-EasyPhoto#158]
![image](https://github.com/aigc-apps/sd-webui-EasyPhoto/assets/92557104/5f8ce7d9-9bc4-4871-b896-d81f4f9a3030)
请问这个怎么解决，这几个库都下不下来

**Comment by wuziheng** [comment]
@bubbliiiing  这个问题有统一的答案么，在autodl上的镜像，是不是要update一下

**Comment by wuziheng** [comment]
请问你使用的是 https://www.codewithgpu.com/i/aigc-apps/sd-webui-EasyPhoto/sd-webui-EasyPhoto
这个镜像么？
