### ISSUE TITLE
Does the obtained Lora overfit

### ISSUE THREAD

**Issue by QJieWang** [aigc-apps/sd-webui-EasyPhoto#162]
I have also tried training portraits myself. When there are few images, it is very easy to overfit if you want to ensure the similarity of the characters. This is reflected in scenes with cues for actions like turning the face sideways or looking up, where the desired effect is not achieved. So, I would like to ask, when EasyPhoto implements few-shot Lora training, are there any particularly good techniques? Does the obtained Lora overfit (only showing the front face without the side profile)?

**Comment by wuziheng** [comment]
EN:
You mentioned some issues that we have made some attempts to address.

In EasyPhoto, Lora is just one means of ensuring similarity. There are also other methods like face fusion, material matching, and keypoint supervision. The final effect is a result of multiple factors; Lora may be important but not the sole determinant.
Our Lora does indeed require 4-10 images, covering a range of angles if possible. Naturally, this limits the angles that can be effectively generated, which is one issue we are looking to address in the future. However, the current results are already quite satisfactory.
There are quite a few Lora training techniques that you can refer to in our arXiv paper.

CN
翻译到英文
你提到的问题我们有过一些尝试，
1.EasyPhoto中Lora只是保证相似度的一个手段，还有其他例如人脸融合，素材匹配，关键点监督等手段，最终的效果是多重作用的，lora 可能很重要，但不完全决定性作用。
2. 我们的lora 确实需要4~10张图片，大致涵盖一些角度最好。当然对应在生成的时候能解决的角度也会少一些，这是未来会试图更好解决的问题之一，但当前的效果就还可以了
3.  有比较多的Lora训练技巧可以参考我们的arxiv。
