### ISSUE TITLE
训练完成后，inference找不到uers id

### ISSUE THREAD

**Issue by jjboy0524** [aigc-apps/sd-webui-EasyPhoto#164]
昨晚机器跑了一夜，跑到早上8点的时候，好像是实验室断网了，log里面显示790/800。Failed to obtain Lora after training, please check the training process.
但是我看权重文件夹里面，有check-point-800的权重文件，所以应该是训练完了的，但就是不显示uesr id

**Comment by jjboy0524** [comment]
但是权重文件里面并没有像你视频那样，xxx-safetensor这样的权重文件。只有8个check point文件以及pytorch_lora_weights.safetensors

**Comment by wuziheng** [comment]
那就是在训练之后挂掉了，我们会在训练后经过一些测试和模型融合以及几张样例图片输出，产出xxx-safetensors。这个过程没有成功执行。

可以再完整检测一遍训练，复现错误，提供相关log
