### ISSUE TITLE
希望对低显存用户提供的友好性改进

### ISSUE THREAD

**Issue by yunwuhai** [aigc-apps/sd-webui-EasyPhoto#166]
低显存用户在进行换脸时容易爆内存，这种情况如果是在图生图界面可以使用Tiled Diffusion插件来解决，然而目前EasyPhoto是直接在插件界面进行的且并不支持Tiled Diffusion，致使矛盾无法解决。
在技术层面是否可以在插件界面内部提供一些帮助低显存用户的方案，或者提供一种方案能够在图生图界面进行使用本插件，以提供更佳丰富的支持功能？

**Comment by wuziheng** [comment]
收到了您的建议
1. diffusion 似乎是我们最大的显存开销，但实际可能还有facefusion，这个需要仔细测量一下。
2. sdwebui生态下，我们用了xformers，准确说是尝试了，后续我们可能会通过改整体框架来降低对其他模型的依赖来修复这个问题。
