### ISSUE TITLE
SDWebUI 前端断连接后，后端任然在训练，该怎么办？

### ISSUE THREAD

**Issue by wuziheng** [aigc-apps/sd-webui-EasyPhoto#17]
问题描述：

1. 训练时间过长，SDWebUI前端断开连接后，后台依然在训练，刷新前端却没有任何提示，该怎么办

当前版本，不要重复提交，观察后台log，等待训练结束后，去infer界面可以正常推理。

TODO：前端提供一个log 显示功能，重连后能够不断刷新出后台的训练log，帮助用户定位？

**Comment by wuziheng** [comment]
solved by 
https://github.com/aigc-apps/sd-webui-EasyPhoto/pull/18

**Comment by bubbliiiing** [comment]
Already Merge.
