### ISSUE TITLE
在使用多人图像功能时人脸周围总是会有一个框

### ISSUE THREAD

**Issue by shynesss** [aigc-apps/sd-webui-EasyPhoto#177]

**Comment by wuziheng** [comment]
请提供图片，但据我所知， 这是一个已知的bug， 可以参考代码中的
https://github.com/aigc-apps/sd-webui-EasyPhoto/blob/63e5f933725eae8d1a5cbb69fc0f20d3447e1a6d/scripts/easyphoto_infer.py#L279C5-L279C30


multi_user_facecrop_ratio和multi_user_safecrop_ratio， 你可以试着把他们分别调整到1.3 和0.95再试试
