### ISSUE TITLE
完全离线运行本插件

### ISSUE THREAD

**Issue by MultiChen** [aigc-apps/sd-webui-EasyPhoto#184]
我是在完全未联网的情况下运行的sd-webui，装上本插件后，似乎一直在通过api调用/predict与/reset，导致甚至无法在setting里面保存设置后重载UI。

**Comment by wuziheng** [comment]
似乎可以通过关闭log 监控，来去掉这个部分, @bubbliiiing  是这个问题么。

**Comment by MultiChen** [comment]
> 似乎可以通过关闭log 监控，来去掉这个部分, @bubbliiiing 是这个问题么。

之前那个issue我也看了，但是未找到在哪里关闭log监控。

**Comment by MultiChen** [comment]
> > 似乎可以通过关闭log 监控，来去掉这个部分, @bubbliiiing 是这个问题么。
> 
> 之前那个issue我也看了，但是未找到在哪里关闭log监控。

注释掉easyphoto-sd-webui/scripts/easyphoto_ui.py
252、253行，就可以了。
