### ISSUE TITLE
使用推理接口的时候报错missing 2 required positional arguments: 'sd_xl_resolution' and 'tabs'"

### ISSUE THREAD

**Issue by humiao1993** [aigc-apps/sd-webui-EasyPhoto#205]
^[{'message': "Infer error, error info:easyphoto_infer_forward() missing 2 required positional arguments: 'sd_xl_resolution' and 'tabs'", 'outputs': [], 'face_id_outputs': []}

这是我传递的参数
{
        "user_ids": ["zbxgirl"],
        "sd_model_checkpoint": "Chilloutmix-Ni-pruned-fp16-fix.safetensors",
        "init_image": encoded_image,

        "first_diffusion_steps": 50,
        "first_denoising_strength": 0.45,
        "second_diffusion_steps": 20,
        "second_denoising_strength": 0.35,
        "crop_face_preprocess": True,

        "before_face_fusion_ratio": 0.5,
        "after_face_fusion_ratio": 0.5,
        "apply_face_fusion_before": True,
        "apply_face_fusion_after": True,

        "color_shift_middle": True,
        "color_shift_last": True,
        "super_resolution": False,
        "background_restore": False,
        "sd_xl_input_prompt": "",
        "sd_xl_resolution": "(1024, 1024)",
        "tabs": 3,
        "seed": -1
    }

**Comment by wuziheng** [comment]
更新到最新的版本，这个问题已经修复。
