### ISSUE TITLE
训练数据迁移

### ISSUE THREAD

**Issue by hanshaoUi** [aigc-apps/sd-webui-EasyPhoto#208]
其它电脑训练完成的模型迁移文件夹到另一台电脑，无法加载到已训练的模型![image](https://github.com/aigc-apps/sd-webui-EasyPhoto/assets/54573836/9f518e58-deff-43db-a0dc-02513441ca34)

**Comment by wuziheng** [comment]
https://github.com/aigc-apps/sd-webui-EasyPhoto/issues/154
