### ISSUE TITLE
FIND was unable to find an engine to execute this computation

### ISSUE THREAD

**Issue by gcr1992** [aigc-apps/sd-webui-EasyPhoto#217]
环境：
SD1.6
pytorch2.1.0
cudnn:  cudnn-linux-x86_64-8.9.4.25_cuda12-archive.tar.xz

在跑easyPhoto的过程报如下错误：

/usr/local/cuda-12.2/lib64/libcudnn_cnn_train.so.8: undefined symbol: _ZN5cudnn3cnn34layerNormFwd_execute_internal_implERKNS_7backend11VariantPackEP11CUstream_stRNS0_18LayerNormFwdParamsERKNS1_20NormForwardOperationEmb, version libcudnn_cnn_infer.so.8
Traceback (most recent call last):
  File "/anaconda/ai/stable-diffusion-webui-1.6.0/extensions/sd-webui-EasyPhoto-main/scripts/train_kohya/train_lora.py", line 1467, in <module>
    main()
  File "/anaconda/ai/stable-diffusion-webui-1.6.0/extensions/sd-webui-EasyPhoto-main/scripts/train_kohya/utils/gpu_info.py", line 173, in wrapper
    result = func(*args, **kwargs)
  File "/anaconda/ai/stable-diffusion-webui-1.6.0/extensions/sd-webui-EasyPhoto-main/scripts/train_kohya/train_lora.py", line 1285, in main
    accelerator.backward(loss)
  File "/anaconda/anaconda3/envs/aidraw/lib/python3.10/site-packages/accelerate/accelerator.py", line 1851, in backward
    self.scaler.scale(loss).backward(**kwargs)
  File "/anaconda/anaconda3/envs/aidraw/lib/python3.10/site-packages/torch/_tensor.py", line 492, in backward
    torch.autograd.backward(
  File "/anaconda/anaconda3/envs/aidraw/lib/python3.10/site-packages/torch/autograd/__init__.py", line 251, in backward
    Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
RuntimeError: FIND was unable to find an engine to execute this computation
=======================================================
我在网上搜了下，大部分说的cudnn配置问题，也有说版本问题

但是：
           print(torch.backends.cudnn.version()) 能够正常打印8904
           ControlNet 也能够正常使用。

如果我降低Cudnn版本，会报入下错误，所以感觉应该不是版本问题

RuntimeError: cuDNN version incompatibility: PyTorch was compiled  against (8, 9, 2) but found runtime version (8, 8, 1). PyTorch already comes bundled with cuDNN. One option to resolvg this error is to ensure PyTorch can find the bundled cuDNN.Looks like your LD_LIBRARY_PATH contains incompatible version of cudnnPlease either remove it from the path or install cudn(8, 9, 2)

**Comment by wuziheng** [comment]
提供一下accelerate 版本

**Comment by gcr1992** [comment]
> 提供一下accelerate 版本

accelerate==0.21.0

**Comment by wuziheng** [comment]
确认几个事情
1. 你在linux环境？
2. 能够尝试降低pytorch版本，这个bug看起来似乎是torch 反传的报错，你能否降低一个更为稳定的torch+cudnn+accelerate版本。我为你提供一下我的版本。

**Comment by gcr1992** [comment]
> 确认几个事情
> 
> 1. 你在linux环境？
> 2. 能够尝试降低pytorch版本，这个bug看起来似乎是torch 反传的报错，你能否降低一个更为稳定的torch+cudnn+accelerate版本。我为你提供一下我的版本。

1 linux环境
2.用的StableDiffusion 1.6 ，麻烦提供一下相关版本，我这边评估下。感谢

**Comment by wuziheng** [comment]
NVIDIA-SMI 525.105.17   Driver Version: 525.105.17   CUDA Version: 12.0
torch                        2.0.0+cu117
accelerate                   0.18.0
![截屏2023-11-01 上午10 12 22](https://github.com/aigc-apps/sd-webui-EasyPhoto/assets/11889926/c09d39c9-5bb5-4d0f-b205-9b02f3f75304)

上面是测试机器1

**Comment by wuziheng** [comment]
![igElAqNwbmcDAQTNAsQFQAbaACOEAaQhAVZNAqqsuCNyDXqRY54_A88AAAGLiKopPATOAAxcpQfOCkbgqggACgQLzabk png_720x720q90](https://github.com/aigc-apps/sd-webui-EasyPhoto/assets/11889926/e3d09376-226b-49e5-9fac-c540ec2cb623)
torch                         2.0.1+cu118
accelerate                    0.21.0
NVIDIA-SMI 525.105.17   Driver Version: 525.105.17   CUDA Version: 12.0
测试环境2

**Comment by gcr1992** [comment]
> ![igElAqNwbmcDAQTNAsQFQAbaACOEAaQhAVZNAqqsuCNyDXqRY54_A88AAAGLiKopPATOAAxcpQfOCkbgqggACgQLzabk png_720x720q90](https://user-images.githubusercontent.com/11889926/279557067-e3d09376-226b-49e5-9fac-c540ec2cb623.jpg) torch 2.0.1+cu118 accelerate 0.21.0 NVIDIA-SMI 525.105.17 Driver Version: 525.105.17 CUDA Version: 12.0 测试环境2

好的，感谢

**Comment by bubbliiiing** [comment]
在
https://github.com/aigc-apps/sd-webui-EasyPhoto/pull/226 
修复

**Comment by bubbliiiing** [comment]
在
https://github.com/aigc-apps/sd-webui-EasyPhoto/pull/226 
修复
