### ISSUE TITLE
Adding Code of Conduct to repo

### ISSUE THREAD

**Issue by mohitd404** [aigc-apps/sd-webui-EasyPhoto#220]
why code-of-conduct:- We propose adding a comprehensive Code of Conduct to our repository to ensure a safe, respectful, and inclusive environment for all contributors and users. This code will  serve as a guideline for behavior, promoting diversity, reducing conflicts, and attracting a wider range of perspectives.

**Issue type**

- [✅] Docs

@wuziheng  If you were planning this issue kindly assign it to me! I would love to work on it ! Thank you !

**Comment by wuziheng** [comment]
reply on your PR
