### ISSUE TITLE
在api.py第44行,保存PNG图片为jpeg时出错

### ISSUE THREAD

**Issue by seakingii** [aigc-apps/sd-webui-EasyPhoto#229]
44行:
`instance_image.save(save_path)
`
我通过API,上传的图像是PNG的,在这一步出错:

**OSError: cannot write mode RGBA as JPEG**

**Comment by wuziheng** [comment]
可以通过一个处理去把RGBA转成RGB，然后再save 成jpg，也可以手动修改成png后缀。我们会修复一下。
