### ISSUE TITLE
ERROR:root:Photo skin_retouching error, error info: 'NoneType' object is not callable

### ISSUE THREAD

**Issue by seekme-ai** [aigc-apps/sd-webui-EasyPhoto#231]
训练时报错，寻求原因和解决方案，谢谢

**Comment by wuziheng** [comment]
这个报错理论上不会中断训练，这个报错是因为没有skin_retouching 这个模型，一般有2个原因
1. 网络不同导致modelscope模型无法下载
2. 部分机器型号问题，导致无法正常load 模型
推荐你在训练中关掉 skin_retouching 即可

**Comment by seekme-ai** [comment]
> 这个报错理论上不会中断训练，这个报错是因为没有skin_retouching 这个模型，一般有2个原因
> 
> 1. 网络不同导致modelscope模型无法下载
> 2. 部分机器型号问题，导致无法正常load 模型
>    推荐你在训练中关掉 skin_retouching 即可

谢谢，抽空试下
