### ISSUE TITLE
Error occurred when sdxl inference with “face shape match” radio checked

### ISSUE THREAD

**Issue by DancingFox** [aigc-apps/sd-webui-EasyPhoto#240]
![IMG_8939](https://github.com/aigc-apps/sd-webui-EasyPhoto/assets/6283792/9c88045c-05ff-4dbc-983a-f9d6c392f06f)
error screenshoot ↑

**Comment by DancingFox** [comment]
@hkunzhe

**Comment by wuziheng** [comment]
Thanks, for more information, 
1.which model you use, XL or 1.5
2. could your please provide your template image

**Comment by wuziheng** [comment]
this is a bug~
