### ISSUE TITLE
TypeError: ClusterConfig.__init__() got an unexpected keyword argument 'debug'

### ISSUE THREAD

**Issue by scarlett5945** [aigc-apps/sd-webui-EasyPhoto#243]
跑几十秒后前端报错：Failed to obtain Lora after training, please check the training process.
2023-11-08 18:37:12,960 - modelscope - INFO - model inference done
2023-11-08 18:37:12,960 - modelscope - WARNING - task face_recognition output keys are missing
 20%|██        | 1/5 [00:01<00:04,  1.03s/it]2023-11-08 18:37:13,216 - modelscope - INFO - model inference done
 40%|████      | 2/5 [00:01<00:01,  1.74it/s]2023-11-08 18:37:13,465 - modelscope - INFO - model inference done
 60%|██████    | 3/5 [00:01<00:00,  2.35it/s]2023-11-08 18:37:13,713 - modelscope - INFO - model inference done
 80%|████████  | 4/5 [00:01<00:00,  2.81it/s]2023-11-08 18:37:13,952 - modelscope - INFO - model inference done
100%|██████████| 5/5 [00:02<00:00,  2.47it/s]
5it [00:01,  2.91it/s]
Traceback (most recent call last):
  File "/data/miniconda3/envs/env-novelai/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/data/miniconda3/envs/env-novelai/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/data/miniconda3/envs/env-novelai/lib/python3.10/site-packages/accelerate/commands/launch.py", line 989, in <module>
    main()
  File "/data/miniconda3/envs/env-novelai/lib/python3.10/site-packages/accelerate/commands/launch.py", line 985, in main
    launch_command(args)
  File "/data/miniconda3/envs/env-novelai/lib/python3.10/site-packages/accelerate/commands/launch.py", line 957, in launch_command
    args, defaults, mp_from_config_flag = _validate_launch_command(args)
  File "/data/miniconda3/envs/env-novelai/lib/python3.10/site-packages/accelerate/commands/launch.py", line 821, in _validate_launch_command
    defaults = load_config_from_file(args.config_file)
  File "/data/miniconda3/envs/env-novelai/lib/python3.10/site-packages/accelerate/commands/config/config_args.py", line 72, in load_config_from_file
    return config_class.from_yaml_file(yaml_file=config_file)
  File "/data/miniconda3/envs/env-novelai/lib/python3.10/site-packages/accelerate/commands/config/config_args.py", line 135, in from_yaml_file
    return cls(**config_dict)
TypeError: ClusterConfig.__init__() got an unexpected keyword argument 'debug'

**Comment by LaowangNineTT** [comment]
> 跑几十秒后前端报错：Failed to obtain Lora after training, please check the training process. 2023-11-08 18:37:12,960 - modelscope - INFO - model inference done 2023-11-08 18:37:12,960 - modelscope - WARNING - task face_recognition output keys are missing 20%|██ | 1/5 [00:01<00:04, 1.03s/it]2023-11-08 18:37:13,216 - modelscope - INFO - model inference done 40%|████ | 2/5 [00:01<00:01, 1.74it/s]2023-11-08 18:37:13,465 - modelscope - INFO - model inference done 60%|██████ | 3/5 [00:01<00:00, 2.35it/s]2023-11-08 18:37:13,713 - modelscope - INFO - model inference done 80%|████████ | 4/5 [00:01<00:00, 2.81it/s]2023-11-08 18:37:13,952 - modelscope - INFO - model inference done 100%|██████████| 5/5 [00:02<00:00, 2.47it/s] 5it [00:01, 2.91it/s] Traceback (most recent call last): File "/data/miniconda3/envs/env-novelai/lib/python3.10/runpy.py", line 196, in _run_module_as_main return _run_code(code, main_globals, None, File "/data/miniconda3/envs/env-novelai/lib/python3.10/runpy.py", line 86, in _run_code exec(code, run_globals) File "/data/miniconda3/envs/env-novelai/lib/python3.10/site-packages/accelerate/commands/launch.py", line 989, in main() File "/data/miniconda3/envs/env-novelai/lib/python3.10/site-packages/accelerate/commands/launch.py", line 985, in main launch_command(args) File "/data/miniconda3/envs/env-novelai/lib/python3.10/site-packages/accelerate/commands/launch.py", line 957, in launch_command args, defaults, mp_from_config_flag = _validate_launch_command(args) File "/data/miniconda3/envs/env-novelai/lib/python3.10/site-packages/accelerate/commands/launch.py", line 821, in _validate_launch_command defaults = load_config_from_file(args.config_file) File "/data/miniconda3/envs/env-novelai/lib/python3.10/site-packages/accelerate/commands/config/config_args.py", line 72, in load_config_from_file return config_class.from_yaml_file(yaml_file=config_file) File "/data/miniconda3/envs/env-novelai/lib/python3.10/site-packages/accelerate/commands/config/config_args.py", line 135, in from_yaml_file return cls(**config_dict) TypeError: ClusterConfig.**init**() got an unexpected keyword argument 'debug'

@scarlett5945 

我的问题解决了，你可以看下你本机的 default_config.yaml 路径，我的问题和你一样，但是后面我查询了一下是因为在这里使用的 default_config.yaml 是 C:\{Users}\.cache\huggingface\acceleratedefault_config.yaml，正常我理解应该用 C:\{Users}\AppData\Local\huggingface\accelerate\default_config.yaml，最快解决的方案是打开你的 C:\{Users}\.cache\huggingface\acceleratedefault_config.yaml，找到是否存在debug这个参数，然后把这个参数注释掉。

![image](https://github.com/aigc-apps/sd-webui-EasyPhoto/assets/3386972/e20760d3-cae8-4d9a-aa0c-462d988d22c1)

**Comment by wuziheng** [comment]
感谢你的解答， 一般 debug 参数缺失 就是由于
accelerate版本问题，或者默认问题导致的

**Comment by Feeling-z** [comment]
> > 跑几十秒后前端报错：Failed to obtain Lora after training, please check the training process. 2023-11-08 18:37:12,960 - modelscope - INFO - model inference done 2023-11-08 18:37:12,960 - modelscope - WARNING - task face_recognition output keys are missing 20%|██ | 1/5 [00:01<00:04, 1.03s/it]2023-11-08 18:37:13,216 - modelscope - INFO - model inference done 40%|████ | 2/5 [00:01<00:01, 1.74it/s]2023-11-08 18:37:13,465 - modelscope - INFO - model inference done 60%|██████ | 3/5 [00:01<00:00, 2.35it/s]2023-11-08 18:37:13,713 - modelscope - INFO - model inference done 80%|████████ | 4/5 [00:01<00:00, 2.81it/s]2023-11-08 18:37:13,952 - modelscope - INFO - model inference done 100%|██████████| 5/5 [00:02<00:00, 2.47it/s] 5it [00:01, 2.91it/s] Traceback (most recent call last): File "/data/miniconda3/envs/env-novelai/lib/python3.10/runpy.py", line 196, in _run_module_as_main return _run_code(code, main_globals, None, File "/data/miniconda3/envs/env-novelai/lib/python3.10/runpy.py", line 86, in _run_code exec(code, run_globals) File "/data/miniconda3/envs/env-novelai/lib/python3.10/site-packages/accelerate/commands/launch.py", line 989, in main() File "/data/miniconda3/envs/env-novelai/lib/python3.10/site-packages/accelerate/commands/launch.py", line 985, in main launch_command(args) File "/data/miniconda3/envs/env-novelai/lib/python3.10/site-packages/accelerate/commands/launch.py", line 957, in launch_command args, defaults, mp_from_config_flag = _validate_launch_command(args) File "/data/miniconda3/envs/env-novelai/lib/python3.10/site-packages/accelerate/commands/launch.py", line 821, in _validate_launch_command defaults = load_config_from_file(args.config_file) File "/data/miniconda3/envs/env-novelai/lib/python3.10/site-packages/accelerate/commands/config/config_args.py", line 72, in load_config_from_file return config_class.from_yaml_file(yaml_file=config_file) File "/data/miniconda3/envs/env-novelai/lib/python3.10/site-packages/accelerate/commands/config/config_args.py", line 135, in from_yaml_file return cls(**config_dict) TypeError: ClusterConfig.**init**() got an unexpected keyword argument 'debug'
> 
> @scarlett5945
> 
> 你可以看下你本机的 default_config.yaml 路径，我的问题和你一样，找到你代码引用的 default_config.yaml 文件位置，找到是否存在 debug 这个参数，然后把这个参数注释掉。
> 
> ![image](https://private-user-images.githubusercontent.com/3386972/281976952-e20760d3-cae8-4d9a-aa0c-462d988d22c1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE2OTU0NjAsIm5iZiI6MTcwMTY5NTE2MCwicGF0aCI6Ii8zMzg2OTcyLzI4MTk3Njk1Mi1lMjA3NjBkMy1jYWU4LTRkOWEtYWEwYy00NjJkOTg4ZDIyYzEucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQUlXTkpZQVg0Q1NWRUg1M0ElMkYyMDIzMTIwNCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyMzEyMDRUMTMwNjAwWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NzJiZGFiODk0ODI1MjgwYjBmMTY2NTI5YmNjNDkwMWYyOTU5Yzc4NjI3YWY4ZjlhOWY0Y2JkYmRmNjFlNjQ5YSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.Nj_TB4ENy4uh-OfYpUcWNiBOKbypqaMCPBNFRL014fs)

你好，请问我也遇到这个问题TypeError: ClusterConfig.__init__() got an unexpected keyword argument 'debug'。但是我打开 default_config.yaml ，没有你说的要删除的参数，要怎么办呢，谢谢！
![未标题-1](https://github.com/aigc-apps/sd-webui-EasyPhoto/assets/152842321/6156166d-a55f-4957-9889-55f2556efdf0)
![未标题-2](https://github.com/aigc-apps/sd-webui-EasyPhoto/assets/152842321/60f73c11-1bd4-41bf-9514-d7e15378ae29)
