### ISSUE TITLE
低级询问：关于autodl9月部署的镜像中easyphoto版本比较低且不能正确更新的问题；

### ISSUE THREAD

**Issue by yinglee712** [aigc-apps/sd-webui-EasyPhoto#248]
在autodl中使用9月份上传的镜像部署easyphoto，版本是ec33ad0e；目前最新版本是d121f41；

1，新版本有增强脸部的功能；想快速使用但是部署挺麻烦的；
2，想要一份11月份部署的镜像；

为何提出这个问题？
1，按照简易流程使easyphoto更新版本，但不知为何没有正确更新。进入云端发现版本依旧是ec33ad0e。
![image](https://github.com/aigc-apps/sd-webui-EasyPhoto/assets/138325653/587c3ca1-365c-4d38-8796-34ee6bf85f1d)

help！

**Comment by yinglee712** [comment]
![image](https://github.com/aigc-apps/sd-webui-EasyPhoto/assets/138325653/5f61c432-0b71-4398-ae11-dc43f58da491)

**Comment by yinglee712** [comment]
喔，我发现可以用网盘接入功能，手动置入最新版本的easyphoto，这下可以正常使用了，

**Comment by wuziheng** [comment]
感谢，我们会在最近完成大的这几个功能(XL,Video)的合并后，重新整理AutoDL的镜像，谢谢您的关注。
