### ISSUE TITLE
关于 diffusers 的版本

### ISSUE THREAD

**Issue by hotick** [aigc-apps/sd-webui-EasyPhoto#253]
目前 diffusers 只能用 0.18.2，但其它插件要用到最新版 0.23.0。
这只能两个插件二选一么？有没有更好的办法，或者开发者们辛苦点弄一下？

**Comment by wuziheng** [comment]
应该是可以提升的，我们最近测一下吧。之前是因为accelerate和训练版本的问题

**Comment by hotick** [comment]
我在 install.py 里改成最新的 0.23.0 版，运行没发现错误提示，暂时正常。而原本因此冲突的 插件 LCM 也正常了。

**Comment by wuziheng** [comment]
感谢您的建议，我们会在下周开始升级0.23 和LCM，欢迎到时候一起验证。

**Comment by wuziheng** [comment]
@hotick 
请检查你的训练过程
![截屏2023-11-20 下午5 12 32](https://github.com/aigc-apps/sd-webui-EasyPhoto/assets/11889926/86fd793c-af81-4c15-984e-19c08e295391)
大于0.18.2的版本会在训练中，无法训练unet的lora，这是因为diffusers 升级导致的，从而导致Lora 特别差，不像。这个问题我们会尽快修复。并争取完成升级。

**Comment by wuziheng** [comment]
try to solve in https://github.com/aigc-apps/sd-webui-EasyPhoto/pull/269

**Comment by bubbliiiing** [comment]
麻烦尝试使用[diffusers_version_fix](https://github.com/aigc-apps/sd-webui-EasyPhoto/tree/diffusers_version_fix)分支。

**Comment by wuziheng** [comment]
我们已经在
https://github.com/aigc-apps/sd-webui-EasyPhoto/pull/311
https://github.com/aigc-apps/sd-webui-EasyPhoto/pull/310

两个PR 修复，并升级到了高版本

**Comment by hotick** [comment]
> 我们已经在 #311 #310
> 
> 两个PR 修复，并升级到了高版本

非常感谢
