### ISSUE TITLE
警告和错误

### ISSUE THREAD

**Issue by danliangsky** [aigc-apps/sd-webui-EasyPhoto#255]
ERROR:root:Photo skin_retouching error, error info: 'NoneType' object is not callable
ERROR:root:Photo skin_retouching error, error info: 'NoneType' object is not callable

WARNING - task face_recognition input definition is missing
WARNING - task face_recognition output keys are missing

这些是不是没有影响呢？

还有为什么我推理速度慢得跟狗一样，用的4090

**Comment by wuziheng** [comment]
1. 前者的问题说明你的这个skin_retouching没有下载成功或者加载成功，常见问题有2个，a.到modelscope 的网有点小问题，b 你的环境跑这个model容易挂， 但无伤大雅，影响不大
2.  慢的和狗一样，一般，我是A10 和4090差不太多，我一张图大概是20s 左右。确实很慢因为流程太长了，后续我们在看简化模型流程和 引入LCM，目标是做到5s内，在1月前

**Comment by danliangsky** [comment]
> 1. 前者的问题说明你的这个skin_retouching没有下载成功或者加载成功，常见问题有2个，a.到modelscope 的网有点小问题，b 你的环境跑这个model容易挂， 但无伤大雅，影响不大
> 2. 慢的和狗一样，一般，我是A10 和4090差不太多，我一张图大概是20s 左右。确实很慢因为流程太长了，后续我们在看简化模型流程和 引入LCM，目标是做到5s内，在1月前

啊这，我一张图要几分钟。。。感觉哪里没弄对呢，关闭了高分辨率放大
