### ISSUE TITLE
自定義tag

### ISSUE THREAD

**Issue by karta0655127** [aigc-apps/sd-webui-EasyPhoto#258]
請問有辦法在訓練前加入字定義的tag嗎？比如人名之類的
謝謝

**Comment by wuziheng** [comment]
可以的，但是需要修改代码，easyphoto_config.py 里面的validation_prompt就是我们的关键字，然后我们最近会有一些更新，可能会修改这个机制。但在那之前可以修改这个。

**Comment by steve-0122** [comment]
了解～所以我只要修改validation_prompt裡面的tag，就可以讓我訓練好的模型帶有我設定的tag對吧？
