### ISSUE TITLE
Have to add models to huggingface

### ISSUE THREAD

**Issue by stqwzr** [aigc-apps/sd-webui-EasyPhoto#259]
Hi, thank you for sharing!

But, could you add `face_landmarks.pth`, `flownet.pkl` models to huggingface please

**Comment by wuziheng** [comment]
OK，I'm going to add model to huggingface in 24hours

**Comment by zouxinyi0625** [comment]
Our models can be found here: https://huggingface.co/alibaba-pai/pai-easyphoto/tree/main
