### ISSUE TITLE
插件 训练的时候报error但不停止，推测的时候报错且停止

### ISSUE THREAD

**Issue by Baiiley** [aigc-apps/sd-webui-EasyPhoto#275]
![训练时](https://github.com/aigc-apps/sd-webui-EasyPhoto/assets/54013952/71142f54-6b1c-4718-beb8-2200fbe37940)
![推测时](https://github.com/aigc-apps/sd-webui-EasyPhoto/assets/54013952/9275352b-c7ce-4769-8b88-d34ca3212243)

**Comment by yinglee712** [comment]
更新最新版本之后我也出现了同样的问题；

依次进行了以下操作还是没有解决问题：
1，卸载并重装最新版本的controlnet插件；
2，更新更高版本的xformers；
3，去云端部署别的版本的SD的镜像；
------
然后作者教我一招投机取巧的操作，就是把一段代码注释掉，（注释是在前面加#号，不是删掉！）
![image](https://github.com/aigc-apps/sd-webui-EasyPhoto/assets/138325653/5b1f9755-6376-459b-a651-a739d86d0790)
![image](https://github.com/aigc-apps/sd-webui-EasyPhoto/assets/138325653/404cc336-aedd-4757-a62b-84ac77938f0e)
不放心可以备份一份再操作；
------
亲测可行！感谢作者们
