### ISSUE TITLE
OutOfMemoryError: CUDA out of memory(RTX 4080)

### ISSUE THREAD

**Issue by vclin123** [aigc-apps/sd-webui-EasyPhoto#281]
出現以下問題，請問該如何調整(我的顯示卡是RTX 4080)
有時候在跑圖或是訓練模型(XL)時，都會出現以下訊息，請問各位大神該如何處理

OutOfMemoryError: CUDA out of memory. Tried to allocate 11.39 GiB (GPU 0; 15.99 GiB total capacity; 8.01 GiB already allocated; 5.48 GiB free; 8.14 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation. See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF

**Comment by yinglee712** [comment]
不懂就问4080能训得起SDXL？我觉得还是得上4090，你可以镜像作者的easyphoto，才1.25就可以拿下a5000显卡
