### ISSUE TITLE
package requirements

### ISSUE THREAD

**Issue by develop-productivity** [aigc-apps/sd-webui-EasyPhoto#282]
你好，感谢你贡献如此杰出的工作，
你能提供一份`requirments.txt`文件吗？方便我们因为包版本问题进行问题排查。
谢谢！

**Comment by wuziheng** [comment]
似乎这个文件就是
https://github.com/aigc-apps/sd-webui-EasyPhoto/blob/main/install.py

然后就是可以去相关的例如autodl/lanrui-ai 启动一个我们/他们打包好的镜像，然后遇到对不齐的python环境可以在上面对比一下。
