### ISSUE TITLE
在訓練時儲存一個checkpoint後的等待時間

### ISSUE THREAD

**Issue by karta0655127** [aigc-apps/sd-webui-EasyPhoto#284]
我的軟體在訓練時儲存一個checkpoint後
會等待一段很長的時間才會繼續訓練
等待的畫面如下，請問這是正常的嗎？
![image](https://github.com/aigc-apps/sd-webui-EasyPhoto/assets/50021406/eb963aef-dc90-40fd-8357-b73a44931b1b)

另外這是剛開始訓練時出現的訊息
![image](https://github.com/aigc-apps/sd-webui-EasyPhoto/assets/50021406/65be68be-9b91-46ce-a961-57ac3cf5d03b)

**Comment by wuziheng** [comment]
yes,这是正常的你可以通过关闭 验证(close validation)来解决这个问题，在存储ckpt的时候，我们会做一次验证，方便debug和模型融合，但是这个可能会造成等待时间过久，尤其在显存有限的机器上。

**Comment by steve-0122** [comment]
@wuziheng 請問我可以怎麼關閉驗證
是直接在EasyPhoto裡面的UI取消勾選就可以了對嗎？

**Comment by wuziheng** [comment]
> @wuziheng 請問我可以怎麼關閉驗證 是直接在EasyPhoto裡面的UI取消勾選就可以了對嗎？

是的，训练UI有这个选项
