### ISSUE TITLE
Cant use infer with IPA only (without Pretraining Lora)

### ISSUE THREAD

**Issue by farizy4n** [aigc-apps/sd-webui-EasyPhoto#285]
![image](https://github.com/aigc-apps/sd-webui-EasyPhoto/assets/145122436/6c4df0fa-bb02-44b9-a645-a2b2bce05883)

> To use IP-Adapter Control, please upgrade sd-webui-controlnet to the latest version.

always show like that. I dont know whats worng with that. im use the lastest ControlNet version, git pull to, and nothing happen to me. Any one case?

**Comment by hkunzhe** [comment]
@farizy4n, can you provide detailed inference options and extension informations?

**Comment by farizy4n** [comment]
> @farizy4n, can you provide detailed inference options and extension informations?

![gambar](https://github.com/aigc-apps/sd-webui-EasyPhoto/assets/145122436/00ec150d-e2d0-4361-b9ae-f2c9c95a3131)

**Comment by farizy4n** [comment]
FIX
`git pull` to all extension.
