### ISSUE TITLE
Hugging Face can not work

### ISSUE THREAD

**Issue by xuyu666** [aigc-apps/sd-webui-EasyPhoto#287]
![image](https://github.com/aigc-apps/sd-webui-EasyPhoto/assets/49869475/662707af-eeaf-441e-9563-8358ba79c5d3)

![image](https://github.com/aigc-apps/sd-webui-EasyPhoto/assets/49869475/697bd3e3-0226-4b74-9204-cc8d500189e9)

**Comment by wuziheng** [comment]
we may close the free api， please deploy this extension by your own
