### ISSUE TITLE
无法安装diffusers

### ISSUE THREAD

**Issue by harrymore** [aigc-apps/sd-webui-EasyPhoto#308]
*** Installing requirements for diffusers
***
*** stderr: Traceback (most recent call last):
***   File "D:\projects\sd\sd-webui-aki-v4.5\extensions\sd-webui-EasyPhoto\install.py", line 75, in <module>
***     launch.run_pip("install 'diffusers<=0.23.0'", "requirements for diffusers")
***   File "<enhanced_experience patches.progress.launch>", line 49, in wrapped_run_pip
***   File "D:\projects\sd\sd-webui-aki-v4.5\modules\launch_utils.py", line 138, in run_pip
***     return run(f'"{python}" -m pip {command} --prefer-binary{index_url_line}', desc=f"Installing {desc}", errdesc=f"Couldn't install {desc}", live=live)
***   File "D:\projects\sd\sd-webui-aki-v4.5\modules\launch_utils.py", line 115, in run
***     raise RuntimeError("\n".join(error_bits))
*** RuntimeError: Couldn't install requirements for diffusers.
*** Command: "D:\projects\sd\sd-webui-aki-v4.5\python\python.exe" -m pip install 'diffusers<=0.23.0' --prefer-binary
*** Error code: 1
*** stderr: ϵͳҲָļ

**Comment by wuziheng** [comment]
will fix in https://github.com/aigc-apps/sd-webui-EasyPhoto/pull/310
 you can install diffusers <=0.23.0  by youself
