### ISSUE TITLE
其他机器上训练好的脸部lora直接复制过来没找到

### ISSUE THREAD

**Issue by newbing2088** [aigc-apps/sd-webui-EasyPhoto#322]
你好，其他机器上训练好的脸部lora直接复制过来只在lora下能看到，easyphoto的user id下刷新不到，还需要复制什么文件过来吗？

**Comment by wuziheng** [comment]
https://github.com/aigc-apps/sd-webui-EasyPhoto/wiki/FAQ#10--%E8%AE%AD%E7%BB%83%E5%AE%8C%E7%9A%84lora-%E5%92%8C%E4%BD%BF%E7%94%A8%E5%8F%AF%E4%B8%8D%E5%8F%AF%E4%BB%A5%E6%95%B4%E4%BD%93%E5%B9%B3%E7%A7%BB


github -wiki-faq 搜索迁移，按照指示操作
