### ISSUE TITLE
image similarity score tool 

### ISSUE THREAD

**Issue by t00350320** [aigc-apps/sd-webui-EasyPhoto#328]
image similarity score tool 

[similarity_tool.txt](https://github.com/aigc-apps/sd-webui-EasyPhoto/files/13645104/similarity_tool.txt)

1) rename similarity_tool.txt to similarity_tool.py , 
2) and put it under folder
/mnt/workspace/demos/stable_diffusion_easyphoto/stable-diffusion-webui/extensions/sd-webui-EasyPhoto
3) python similarity_tool.py 

PTAL
thanks !!!

**Comment by wuziheng** [comment]
thanks， we have integrated this similarity tools from first version
