### ISSUE TITLE
能否直接使用 lora作为人物模型？Can I just use LORA as a character model？

### ISSUE THREAD

**Issue by KerenElience** [aigc-apps/sd-webui-EasyPhoto#329]
能直接使用`lora`作为人物模型输入吗，如果能，那对应存放的目录应该在哪呢，或者说训练好的人物模型存放位置。
Can I use `lora` directly as character model input, and if so, where should the corresponding storage directory be, or where the trained character model is stored.

**Comment by wuziheng** [comment]
No youcant ，参考 github-wiki-faq ，搜索迁移， 一个人物除了lora 还需要一张参考图片，至少需要一张。搜索这个答案会找到我们如何从一个EP 训练的模型迁移到别的机器，从而需要的最少的数据。
