### ISSUE TITLE
训练时能不能不下载无关模型

### ISSUE THREAD

**Issue by bigbaldy1128** [aigc-apps/sd-webui-EasyPhoto#339]
您好，我只是想用这个训练自己的Lora，但是开始训练后会下载很多模型，我看都和训练本身无关，例如很多controlnet的模型，还有ChilloutMix-ni-fp16这个模型，我明明选了自己要用的模型，为啥还要下载这个模型呢

**Comment by paradiseHIT** [comment]
因为你不知道你什么时候就在用到这些模型。。。
