### ISSUE TITLE
a bug in easyphoto_infer

### ISSUE THREAD

**Issue by janic716** [aigc-apps/sd-webui-EasyPhoto#341]
https://github.com/aigc-apps/sd-webui-EasyPhoto/blob/d47a2de062a05dcadeee83f140e18fbefb6d79ff/scripts/easyphoto_infer.py#L1224C61-L1224C61

```python
# First diffusion, facial reconstruction
ep_logger.info("Start First diffusion.")
ImageChops.multiply(input_image, input_mask)
if not face_shape_match:
```
the result of "ImageChops.multiply(input_image, input_mask)" is not used

**Comment by bubbliiiing** [comment]
delete already

**Comment by hkunzhe** [comment]
> https://github.com/aigc-apps/sd-webui-EasyPhoto/blob/d47a2de062a05dcadeee83f140e18fbefb6d79ff/scripts/easyphoto_infer.py#L1224C61-L1224C61
> 
> ```python
> # First diffusion, facial reconstruction
> ep_logger.info("Start First diffusion.")
> ImageChops.multiply(input_image, input_mask)
> if not face_shape_match:
> ```
> 
> the result of "ImageChops.multiply(input_image, input_mask)" is not used

Just a typo. It doesn't make a difference to the result.
