### ISSUE TITLE
在sd里用easyphoto 训练lora 会出现问题？？？

### ISSUE THREAD

**Issue by ccIsCool6** [aigc-apps/sd-webui-EasyPhoto#347]
File "D:\AI画图\sd-webui-aki-v4.5\python\lib\site-packages\accelerate\commands\launch.py", line 628, in simple_launcher
    raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)
subprocess.CalledProcessError: Command '['D:\\AI画图\\sd-webui-aki-v4.5\\python\\python.exe', 'D:\\AI画图\\sd-webui-aki-v4.5\\extensions\\sd-webui-EasyPhoto\\scripts\\train_kohya/train_lora.py', '--pretrained_model_name_or_path=extensions\\sd-webui-EasyPhoto\\models\\stable-diffusion-v1-5', '--pretrained_model_ckpt=models\\Stable-diffusion\\realisticVisionV60B1_v60B1VAE(only pep).safetensors', '--train_data_dir=outputs\\easyphoto-user-id-infos\\wjh lora2\\processed_images', '--caption_column=text', '--resolution=512', '--random_flip', '--train_batch_size=1', '--gradient_accumulation_steps=4', '--dataloader_num_workers=0', '--max_train_steps=1000', '--checkpointing_steps=100', '--learning_rate=0.0001', '--lr_scheduler=constant', '--lr_warmup_steps=0', '--train_text_encoder', '--seed=277210', '--rank=128', '--network_alpha=64', '--validation_prompt=easyphoto_face, easyphoto, 1person', '--validation_steps=100', '--output_dir=outputs\\easyphoto-user-id-infos\\wjh lora2\\user_weights', '--logging_dir=outputs\\easyphoto-user-id-infos\\wjh lora2\\user_weights', '--enable_xformers_memory_efficient_attention', '--mixed_precision=fp16', '--template_dir=extensions\\sd-webui-EasyPhoto\\models\\training_templates', '--template_mask', '--merge_best_lora_based_face_id', '--merge_best_lora_name=wjh lora2', '--cache_log_file=D:\\AI画图\\sd-webui-aki-v4.5\\outputs/easyphoto-tmp/train_kohya_log.txt', '--validation']' returned non-zero exit status 1.

为什么老是这样报错啊？真没懂

**Comment by wuziheng** [comment]
去掉你的路径里的中文，这会导致底层依赖可能出现问题。
