### ISSUE TITLE
更新插件后，原有训练好的模型未被展示在模型列表中

### ISSUE THREAD

**Issue by Hanying-Song** [aigc-apps/sd-webui-EasyPhoto#35]

**Comment by wuziheng** [comment]
@Hanying-Song @wuziheng  
1. 这是由于临时文件被clean导致的
2. 当前在extensions/sd-webui-EasyPhoto/models/ids.txt 中手动添加之前的user_id 应该可以搞定
我们会在下一个大更新中修改这个问题

**Comment by bubbliiiing** [comment]
fix
