### ISSUE TITLE
我是MAC用户，正常安装了插件，但是WEBUI中不显示

### ISSUE THREAD

**Issue by leozongmac** [aigc-apps/sd-webui-EasyPhoto#350]
I am a MAC user, I installed this plugin in the extension, but it is not displayed in the webui, why?
我是MAC用户，我在扩展中安装了这个插件，但是在webui中不显示，请问为什么？

**Comment by wuziheng** [comment]
mac暂不支持 ，很多模型都不支持mac 请尝试云端gpu部署
