### ISSUE TITLE
開始訓練人臉前face_id評分流程的程式

### ISSUE THREAD

**Issue by steve-0122** [aigc-apps/sd-webui-EasyPhoto#357]
因為每次在訓練開始前才會知道這次選取的素材相似度高不高
所以想知道是否有可以先單獨知道一批素材相似度的方法

請問目前有介面可以單獨使用開始訓練前為人臉評分的程式流程嗎？
或是我可以怎麼修改程式的內容以達到相同的需求？

如果可以的話我也想知道是否也可以將訓練的流程修改成：
例如相似度大於0.55才將圖片加入訓練
或是相似度前10的圖片才會加入訓練

謝謝
這個插件使用起來真的是方常方便

**Comment by wuziheng** [comment]
谢谢你的高度评价，我给你一个建议
1.https://www.modelscope.cn/models/bubbliiiing/cv_retinafce_recognition/summary
2. https://www.modelscope.cn/models/damo/cv_ir101_facerecognition_cfglint/summary

1 是我们在EasyPhoto使用的模型，是我们自己上传维护的，2是原始官方的，你参考这两个modelscope 模型的使用即可。
可以先跑通2 再尝试1
