### ISSUE TITLE
卸载问题

### ISSUE THREAD

**Issue by Limoting6699** [aigc-apps/sd-webui-EasyPhoto#358]
如果我需要在本地UI页面里面卸载您的插件，我想问下在过程中是否也会同时卸载掉之前安装时候一起下载的那些10几个G的文件。还是当时那些文件需要后面手动在去文件夹里面删除，如果需要手动删除，那我应该去那些对应文件夹删除那些文件。

**Comment by wuziheng** [comment]
理论上那些文件需要手动卸载，参考这个代码源文件，里面对所有的模型的tag 和下载后的对应路径做了一个映射
https://github.com/aigc-apps/sd-webui-EasyPhoto/blob/main/scripts/easyphoto_utils/common_utils.py

例如这个代码
            os.path.join(models_path, f"ControlNet/control_v11p_sd15_openpose.pth"),
            os.path.join(controlnet_cache_path, f"models/control_v11p_sd15_openpose.pth"),

就表示我们下载的 control_v11p_sd15_openpose.pth 可能会在这两个路径之一，需要你自己对应一下。一般来说和sd的默认设置是对齐的。
