### ISSUE TITLE
是否支持纯CPU使用？

### ISSUE THREAD

**Issue by mtide** [aigc-apps/sd-webui-EasyPhoto#359]
SD本体通过--skip-torch-cuda-test 参数可以使用 CPU 推理。
但是本插件训练时，报错： AssertionError: Torch not compiled with CUDA enabled

**Comment by wuziheng** [comment]
不支持，有一些modelscope的模型只有GPU 版本，而且很慢，所以我们设计的时候就没有考虑过纯CPU
