### ISSUE TITLE
人物训练图上传后由正视图照变成了横向的视图照，上传的图片确认是正视图

### ISSUE THREAD

**Issue by RonnieChenR** [aigc-apps/sd-webui-EasyPhoto#36]
![image](https://github.com/aigc-apps/sd-webui-EasyPhoto/assets/90434730/9e2ae3ad-75c1-43e9-9053-562f6cd2bf36)
像这样，然后在预处理照片裁剪人脸的时候也是横向裁剪

![image](https://github.com/aigc-apps/sd-webui-EasyPhoto/assets/90434730/c59c2a39-3687-4e8f-9f2e-8f03377bb8f1)

**Comment by wuziheng** [comment]
1. 这个确实可能是预处理的裁剪问题，理论上不应该存在。
2. 可能进一步麻烦您确认这个影响训练结果么，我觉得如果图片只是个别旋转应该影响不是特别大
3. 方便的话加入群聊，提供这张照片和版本号，我们来对这张图片的预训练的意外旋转定位一下问题。

**Comment by RonnieChenR** [comment]
> 

好的，之前还有碰到过手机直拍的所有上传图片都变成了横向情况，从而训练无法成功。

**Comment by bubbliiiing** [comment]
这个是手机拍摄的问题，很多其它仓库也会存在，需要讨论一下如何去解。

> 1. 这个确实可能是预处理的裁剪问题，理论上不应该存在。
> 2. 可能进一步麻烦您确认这个影响训练结果么，我觉得如果图片只是个别旋转应该影响不是特别大
> 3. 方便的话加入群聊，提供这张照片和版本号，我们来对这张图片的预训练的意外旋转定位一下问题。

**Comment by wuziheng** [comment]
@bubbliiiing @RonnieChenR  那是否在手机拍摄的图片，用户比如用cv2 read 然后save一下 ，再使用我们的repo就可以解决这一问题？

**Comment by wenmengzhou** [comment]
使用PILImage读取下exif的旋转信息，旋转下即可

**Comment by bubbliiiing** [comment]
> 使用PILImage读取下exif的旋转信息，旋转下即可

收到，留作下一步todo

**Comment by wuziheng** [comment]
https://github.com/aigc-apps/sd-webui-EasyPhoto/commit/fbdcd5e7a290666290dd396d2987243dddd138c1

Solve
