### ISSUE TITLE
Infer with IPA only，部分照片换脸的二个问题

### ISSUE THREAD

**Issue by cqflgl** [aigc-apps/sd-webui-EasyPhoto#361]
环境：python 3.10,  CUDA 11.8, pytorch 2.0.1, EasyPhoto是今日安装的最新版本

问题一：点击Photo Inference、Photo2Photo、Single Image Upload，上传第1张图；选择chilloutmix基础模型和Infer with IPA only(without Pretraining Lora)，上传第2张图；点击生成后台打印错误：
2024-01-07 18:10:08,256 - EasyPhoto - 
            Start Generate template                 : 1;
            user_ids                                : ['ipa_control_only', 'none', 'none', 'none', 'none'];
            sd_model_checkpoint                     : Chilloutmix-Ni-pruned-fp16-fix.safetensors;
            input_prompts                           : ['1person, face, portrait, <lora:FilmVelvia3:0.65>, masterpiece, beauty', 'none', 'none', 'none', 'none'];
            before_face_fusion_ratio                : 0.6;
            after_face_fusion_ratio                 : 0.6;
            first_diffusion_steps                   : 50;
            first_denoising_strength                : 0.45;
            second_diffusion_steps                  : 20;
            second_denoising_strength               : 0.3;
            seed                                    : 46868
            crop_face_preprocess                    : True
            apply_face_fusion_before                : True
            apply_face_fusion_after                 : True
            color_shift_middle                      : True
            color_shift_last                        : True
            super_resolution                        : True
            super_resolution_method                 : gpen
            display_score                           : True
            background_restore                      : False
            background_restore_denoising_strength   : 0.35
            makeup_transfer                         : False
            makeup_transfer_ratio                   : 0.5
            skin_retouching_bool                    : False
            face_shape_match                        : False
            ipa_control                             : True
            ipa_weight                              : 0.6
            ipa_image_path                          : /tmp/gradio/tmpdkr1vbb5.png
            ref_mode_choose                         : Infer with IPA only(without Pretraining Lora)
            ipa_only_weight                         : 0.6
            ipa_only_image_path                     : /tmp/gradio/tmpdkr1vbb5.png
        
2024-01-07 18:10:08,599 - EasyPhoto - Start Image resize to 512.0.
2024-01-07 18:10:08,612 - EasyPhoto - Start face detect.
Traceback (most recent call last):
  File "/root/autodl-tmp/stable-diffusion-webui/extensions/sd-webui-EasyPhoto/scripts/easyphoto_infer.py", line 1193, in easyphoto_infer_forward
    min_y = max(int(np.min(y_coords)), 1)
  File "<__array_function__ internals>", line 180, in amin
  File "/root/miniconda3/envs/xl_env/lib/python3.10/site-packages/numpy/core/fromnumeric.py", line 2918, in amin
    return _wrapreduction(a, np.minimum, 'min', axis, None, out,
  File "/root/miniconda3/envs/xl_env/lib/python3.10/site-packages/numpy/core/fromnumeric.py", line 86, in _wrapreduction
    return ufunc.reduce(obj, axis, dtype, out, **passkwargs)
ValueError: zero-size array to reduction operation minimum which has no identity
2024-01-07 18:10:08,967 - EasyPhoto - Template 1 error: Error info is zero-size array to reduction operation minimum which has no identity, skip it.
Cleanup completed.
Reusing loaded model Chilloutmix-Ni-pruned-fp16-fix.safetensors [59ffe2243a] to load AnythingV5.safetensors [a1535d0a42]

问题二：操作和上面一样，有时候会在额头上生成多余的头发，生成多余的牙齿，脸部崩坏，参看第3、4、5张图，请问怎么解决？

![19](https://github.com/aigc-apps/sd-webui-EasyPhoto/assets/62335372/c224711c-35fd-4d9b-980b-d56c48491ca4)
![43](https://github.com/aigc-apps/sd-webui-EasyPhoto/assets/62335372/1ee8a2d5-d98d-4aae-97b8-1d6c8accc648)
![58-35-easyphoto](https://github.com/aigc-apps/sd-webui-EasyPhoto/assets/62335372/22690e62-d402-4588-be37-bb48ee182628)
![71-84-easyphoto](https://github.com/aigc-apps/sd-webui-EasyPhoto/assets/62335372/004e64c8-3041-4177-9f4d-471ba275f054)
![11-83-easyphoto](https://github.com/aigc-apps/sd-webui-EasyPhoto/assets/62335372/d89c5f0d-1c2c-4245-9b96-ac593484f054)

**Comment by wuziheng** [comment]
1. 图1似乎是输入图片没有检测到合适的人脸
2. 第二个问题IPA-Only 的图片是不是包含了一些额外头发的信息，比如显著的发丝，会导致注入比较明显，其次对于生成崩坏，感觉是个很常见的问题，没有特别万能的方案，多抽卡。如果可以去在sliders 这个技术路线里面找一些可能解决的方案

**Comment by cqflgl** [comment]
> 1. 图1似乎是输入图片没有检测到合适的人脸
> 2. 第二个问题IPA-Only 的图片是不是包含了一些额外头发的信息，比如显著的发丝，会导致注入比较明显，其次对于生成崩坏，感觉是个很常见的问题，没有特别万能的方案，多抽卡。如果可以去在sliders 这个技术路线里面找一些可能解决的方案

感谢回复！我这边有20对测试图片，有4对图片存在第一个问题，报错无法换脸，请问这个问题能解决吗？经确认，有4对图片存在多生成头发的问题。
这些问题如果不解决，Infer with IPA only这个功能似乎很难商用吧。

**Comment by wuziheng** [comment]
> > 1. 图1似乎是输入图片没有检测到合适的人脸
> > 2. 第二个问题IPA-Only 的图片是不是包含了一些额外头发的信息，比如显著的发丝，会导致注入比较明显，其次对于生成崩坏，感觉是个很常见的问题，没有特别万能的方案，多抽卡。如果可以去在sliders 这个技术路线里面找一些可能解决的方案
> 
> 感谢回复！我这边有20对测试图片，有4对图片存在第一个问题，报错无法换脸，请问这个问题能解决吗？经确认，有4对图片存在多生成头发的问题。 这些问题如果不解决，Infer with IPA only这个功能似乎很难商用吧。

事实上最近有很多文章似乎在做单图注入，例如PhotoMaker，InstanceID，FACT 以及之前的IP-Adapter，但我个人看过后认为这类的方案似乎在单图无训练的方案下都挺难做到比较高的成功率。所以这个方向的直接商用确实是存疑的。
