### ISSUE TITLE
How to use age slider?

### ISSUE THREAD

**Issue by xbobos** [aigc-apps/sd-webui-EasyPhoto#369]
When I select the age slider, this statement appears:
<lora:age_sd1_sliders:1@0, 0@0.2, 2@0.2, 2@1>
How do I use it?

**Comment by hkunzhe** [comment]
@xbobos, Please refer to [wiki](https://github.com/aigc-apps/sd-webui-EasyPhoto/wiki/Attribute-Edit) for details.
