### ISSUE TITLE
[Windows出现s3报错的打印] C:\arrow\cpp\src\arrow\filesystem\s3fs.cc:2829: 当默认LORA是炼好的，重新启动UI，会出现这代码，以前没出现过？

### ISSUE THREAD

**Issue by newstargo** [aigc-apps/sd-webui-EasyPhoto#37]
activating extra network lora: TypeError
Traceback (most recent call last):
  File "C:\Users\nsg\stable-diffusion-webui\modules\extra_networks.py", line 145, in activate
    extra_network.activate(p, [])
  File "C:\Users\nsg\stable-diffusion-webui\extensions-builtin\Lora\extra_networks_lora.py", line 18, in activate
    p.all_prompts = [x + f"<lora:{additional}:{shared.opts.extra_networks_default_multiplier}>" for x in p.all_prompts]
TypeError: 'NoneType' object is not iterable

**Comment by wuziheng** [comment]
@bubbliiiing  这个我没遇见过，我们一起follow一下，欢迎群里提供截图一起debug。

**Comment by newstargo** [comment]
还有严重的，进了UI，刷新LORA，几分钟都没停下来，版本是1.6.0，是否有兼容问题，这几天被1.6.0的兼容，好多插件都要重装，现在还有些没解决呢

**Comment by newstargo** [comment]
> @bubbliiiing 这个我没遇见过，我们一起follow一下，欢迎群里提供截图一起debug。

进哪个群？

**Comment by wuziheng** [comment]
![erweima](https://github.com/aigc-apps/sd-webui-EasyPhoto/assets/11889926/b712653e-06c5-4f88-bf8f-a66e64cb2f72)
刷新readme，有一个钉钉群

**Comment by newstargo** [comment]
大哥，少用钉钉，有微信群不

**Comment by newstargo** [comment]
C:\arrow\cpp\src\arrow\filesystem\s3fs.cc:2829:  arrow::fs::FinalizeS3 was not called even though S3 was initialized.  This could lead to a segmentation fault at exit, 每次关机都有这个,什么来的

**Comment by bubbliiiing** [comment]
> C:\arrow\cpp\src\arrow\filesystem\s3fs.cc:2829: arrow::fs::FinalizeS3 was not called even though S3 was initialized. This could lead to a segmentation fault at exit, 每次关机都有这个,什么来的

不好意思给你造成了麻烦，这个问题我也遇到过，在应该安装该插件前也存在，我的出现时间是每次运行webui关闭终端或者结束webui是，并不影响使用。这应该是windwos自带的问题。

**Comment by newstargo** [comment]
> > C:\arrow\cpp\src\arrow\filesystem\s3fs.cc:2829: arrow::fs::FinalizeS3 was not called even though S3 was initialized. This could lead to a segmentation fault at exit, 每次关机都有这个,什么来的
> 
> 不好意思给你造成了麻烦，这个问题我也遇到过，在应该安装该插件前也存在，我的出现时间是每次运行webui关闭终端或者结束webui是，并不影响使用。这应该是windwos自带的问题。

新问题，项目和roop好象有冲突，下架项目roop工作正常，再上项目roop就不工作，有遇到过吗

**Comment by bubbliiiing** [comment]
> > > C:\arrow\cpp\src\arrow\filesystem\s3fs.cc:2829: arrow::fs::FinalizeS3 was not called even though S3 was initialized. This could lead to a segmentation fault at exit, 每次关机都有这个,什么来的
> > 
> > 
> > 不好意思给你造成了麻烦，这个问题我也遇到过，在应该安装该插件前也存在，我的出现时间是每次运行webui关闭终端或者结束webui是，并不影响使用。这应该是windwos自带的问题。
> 
> 新问题，项目和roop好象有冲突，下架项目roop工作正常，再上项目roop就不工作，有遇到过吗

请问可以贴出具体的冲突与报错吗？我们没有遇到过，我们会根据冲突情况进行实验，并且在不影响性能的情况下进行修正。不过如果是新问题，欢迎提新的issue，也有助于其它同学定位问题所在。
