### ISSUE TITLE
"No module named 'modelscope'" error

### ISSUE THREAD

**Issue by rowild** [aigc-apps/sd-webui-EasyPhoto#371]
I am on a MacBook Pro M2, 36GB, with the latest Sable-Diffusion-WebUI (Automaticc1111). This error happens when starting the app again after installation. Is there anything I can do to fix this problem?

**Comment by wuziheng** [comment]
we do not support Mac for now， please try some cloud GPU such as lanrui-ai， aliyun-dsw
