### ISSUE TITLE
使用api提交训练任务，或者图片生成任务，是否可以有api查询训练进度或者图片生成进度？

### ISSUE THREAD

**Issue by longquanwjx** [aigc-apps/sd-webui-EasyPhoto#373]
如题

**Comment by wuziheng** [comment]
不会提供这样的工具，和算法本身的需求差距较大，需要用户自行开发，或者使用saas相关的服务
cankao : https://github.com/aigc-apps/sd-webui-EasyPhoto/wiki/SAAS%E2%80%90Aliyun
