### ISSUE TITLE
增加训练集，和样本照片对比

### ISSUE THREAD

**Issue by Wang2220673171** [aigc-apps/sd-webui-EasyPhoto#379]
我每次上穿照片，但貌似只会收录14张照片做训练集，我想多传一些做更精致的lora，

**Comment by wuziheng** [comment]
https://github.com/aigc-apps/sd-webui-EasyPhoto/blob/da0281b92971200f02c7e7a821322eeb978f7d6a/scripts/preprocess.py#L195

修改这个里面的15 并改成你需要的数字，然后使用。
