### ISSUE TITLE
install.py  ModuleNotFoundError: No module named 'aliyunsdkcore'

### ISSUE THREAD

**Issue by cjl84914** [aigc-apps/sd-webui-EasyPhoto#381]
Collecting crcmod>=1.7 (from oss2->modelscope==1.9.3)
  Downloading https://pypi.tuna.tsinghua.edu.cn/packages/6b/b0/e595ce2a2527e169c3bcd6c33d2473c1918e0b7f6826a043ca1245dd4e5b/crcmod-1.7.tar.gz (89 kB)
     ---------------------------------------- 89.7/89.7 kB 2.5 MB/s eta 0:00:00
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'done'
Requirement already satisfied: pycryptodome>=3.4.7 in c:\users\cjl84\appdata\roaming\python\python310\site-packages (from oss2->modelscope==1.9.3) (3.17)
Collecting aliyun-python-sdk-kms>=2.4.1 (from oss2->modelscope==1.9.3)
  Downloading https://pypi.tuna.tsinghua.edu.cn/packages/3d/ea/d88e08bfc4a0aee0111f1f24c98b19107bc6783441e7e944907c77b2243d/aliyun_python_sdk_kms-2.16.2-py2.py3-none-any.whl (94 kB)
     ---------------------------------------- 94.0/94.0 kB 5.2 MB/s eta 0:00:00
Collecting aliyun-python-sdk-core>=2.13.12 (from oss2->modelscope==1.9.3)
  Downloading https://pypi.tuna.tsinghua.edu.cn/packages/1e/e3/8623c0305022610466ded2b0010a7221e9585046116263dd27cb2e56df36/aliyun-python-sdk-core-2.14.0.tar.gz (443 kB)
     -------------------------------------- 443.0/443.0 kB 6.9 MB/s eta 0:00:00
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'error'

stderr:   error: subprocess-exited-with-error

  python setup.py egg_info did not run successfully.
  exit code: 1

  [6 lines of output]
  Traceback (most recent call last):
    File "<string>", line 2, in <module>
    File "<pip-setuptools-caller>", line 34, in <module>
    File "C:\Users\cjl84\AppData\Local\Temp\pip-install-avfi0u_h\aliyun-python-sdk-core_2a8e668401b94395bc2913d9d97ba1c7\setup.py", line 41, in <module>
      VERSION = __import__(PACKAGE).__version__
  ModuleNotFoundError: No module named 'aliyunsdkcore'

**Comment by wuziheng** [comment]
麻烦问一下，您使用的是自己的电脑？ 可以尝试群里提供的秋叶包，似乎安装modelscope 不会遇到这个问题。

**Comment by jinnaluo0** [comment]
失败经验一，按百度上的说法，执行以下命令，全都不好使：
pip3 install --no-cache-dir aliyun-python-sdk-core-v3 -i https://mirrors.aliyun.com/pypi/simple/
pip3 install --no-cache-dir aliyun-python-sdk-core -i https://mirrors.aliyun.com/pypi/simple/
pip install --no-cache-dir aliyun-python-sdk-rds -i https://mirrors.aliyun.com/pypi/simple/
pip3 install --no-cache-diraliyun-python-sdk-ecs -i https://mirrors.aliyun.com/pypi/simple/
pip3 install --no-cache-dir aliyun-python-sdk-dysmsapi -i https://mirrors.aliyun.com/pypi/simple/
pip3 install --no-cache-dir modelscope==1.9.3 -i https://mirrors.aliyun.com/pypi/simple/

失败经验二，我用的秋叶的整合包，换了一个原始的干净的py310文件夹，启动后，会自动安装各种模块，需要花好几分钟时间，但是最后仍然报相同的错误。

成功经验：我用的秋叶的整合包，换了一个原始的干净的py310文件夹，将插件目录下的所有插件都移除，只保留easyphoto,启动程序，后台没有报错，界面上能看到easyphoto页签。此时将其余的插件一个一个地再放回到插件目录，意图寻找有冲突的插件。但是最后发现，后台没有出现任何报错，easyphoto也正常显示。
难道，这插件安装，还分先后顺序吗？？？？？？

另，有人说这个命令好用：pip install aliyun-python-sdk-core-v3==2.13.10，没测试过。
https://github.com/modelscope/modelscope/issues/589

**Comment by cjl84914** [comment]
> 麻烦问一下，您使用的是自己的电脑？ 可以尝试群里提供的秋叶包，似乎安装modelscope 不会遇到这个问题。

我用的是秋叶包

**Comment by cjl84914** [comment]
> 失败经验一，按百度上的说法，执行以下命令，全都不好使： pip3 install --no-cache-dir aliyun-python-sdk-core-v3 -i https://mirrors.aliyun.com/pypi/simple/ pip3 install --no-cache-dir aliyun-python-sdk-core -i https://mirrors.aliyun.com/pypi/simple/ pip install --no-cache-dir aliyun-python-sdk-rds -i https://mirrors.aliyun.com/pypi/simple/ pip3 install --no-cache-diraliyun-python-sdk-ecs -i https://mirrors.aliyun.com/pypi/simple/ pip3 install --no-cache-dir aliyun-python-sdk-dysmsapi -i https://mirrors.aliyun.com/pypi/simple/ pip3 install --no-cache-dir modelscope==1.9.3 -i https://mirrors.aliyun.com/pypi/simple/
> 
> 失败经验二，我用的秋叶的整合包，换了一个原始的干净的py310文件夹，启动后，会自动安装各种模块，需要花好几分钟时间，但是最后仍然报相同的错误。
> 
> 成功经验：我用的秋叶的整合包，换了一个原始的干净的py310文件夹，将插件目录下的所有插件都移除，只保留easyphoto,启动程序，后台没有报错，界面上能看到easyphoto页签。此时将其余的插件一个一个地再放回到插件目录，意图寻找有冲突的插件。但是最后发现，后台没有出现任何报错，easyphoto也正常显示。 难道，这插件安装，还分先后顺序吗？？？？？？
> 
> 另，有人说这个命令好用：pip install aliyun-python-sdk-core-v3==2.13.10，没测试过。 [modelscope/modelscope#589](https://github.com/modelscope/modelscope/issues/589)

这招可以

**Comment by DD-MASTERT** [comment]
遇到了同样的问题，怎么都不行。实测pip install aliyun-python-sdk-core-v3==2.13.10 确实好使

**Comment by xuxucca** [comment]
> 失败经验一，按百度上的说法，执行以下命令，全都不好使： pip3 install --no-cache-dir aliyun-python-sdk-core-v3 -i https://mirrors.aliyun.com/pypi/simple/pip3 install --no-cache-dir aliyun-python-sdk-core-v3 -ihttps://mirrors.aliyun.com/pypi/simple/ pip3 install --no-cache-dir aliyun-python-sdk-core -i https://mirrors.aliyun.com/pypi/simple/pip3 install --no-cache-dir aliyun-python-sdk-core -ihttps://mirrors.aliyun.com/pypi/simple/ pip install --no-cache-dir aliyun-python-sdk-rds -i https://mirrors.aliyun.com/pypi/simple/pip install --no-cache-dir aliyun-python-sdk-rds -ihttps://mirrors.aliyun.com/pypi/simple/ pip3 install --no-cache-diraliyun-python-sdk-ecs -i https://mirrors.aliyun.com/pypi/simple/pip3 install --no-cache-diraliyun-python-sdk-ecs -ihttps://mirrors.aliyun.com/pypi/simple/ pip3 install --no-cache-dir aliyun-python-sdk-dysmsapi -i https://mirrors.aliyun.com/pypi/simple/pip3 install --no-cache-dir aliyun-python-sdk-dysmsapi -ihttps://mirrors.aliyun.com/pypi/simple/ pip3 install --no-cache-dir modelscope==1.9.3 -i https://mirrors.aliyun.com/pypi/simple/pip3 install --no-cache-dir modelscope==1.9.3 -ihttps://mirrors.aliyun.com/pypi/simple/
> 
> 失败经验二，我用的秋叶的整合包，换了一个原始的干净的py310文件夹，启动后，会自动安装各种模块，需要花好几分钟时间，但是最后仍然报相同的错误。
> 
> 成功经验：我用的秋叶的整合包，换了一个原始的干净的py310文件夹，将插件目录下的所有插件都移除，只保留easyphoto,启动程序，后台没有报错，界面上能看到easyphoto页签。此时将其余的插件一个一个地再放回到插件目录，意图寻找有冲突的插件。但是最后发现，后台没有出现任何报错，easyphoto也正常显示。 难道，这插件安装，还分先后顺序吗？？？？？？
> 
> 另，有人说这个命令好用：pip install aliyun-python-sdk-core-v3==2.13.10，没测试过。 [modelscope/modelscope#589](https://github.com/modelscope/modelscope/issues/589)

是的 这个命令好用
