### ISSUE TITLE
Question regarding Training

### ISSUE THREAD

**Issue by Dioskurides** [aigc-apps/sd-webui-EasyPhoto#390]
Hey, i noticed that that the "train" folder in C:\StableDiffusion\stable-diffusion-webui\outputs\easyphoto-user-id-infos\Rouven\processed_images\train only contains 15 image even tho i uploaded 35 for training is there a way to change this?

kind regards

**Comment by wuziheng** [comment]
search 15 or 14 in preprocess， we will do some cluster and filter top15 images for training， you can fix it by your own.

**Comment by wuziheng** [comment]
@Dioskurides  line mark
https://github.com/aigc-apps/sd-webui-EasyPhoto/blob/a5708be54117b874f4602316e0a89a6b3f0761ab/scripts/preprocess.py#L195

**Comment by Dioskurides** [comment]
Thank you!
