### ISSUE TITLE
训练完成的模型如何从云端移植到本地？

### ISSUE THREAD

**Issue by Cyanus000** [aigc-apps/sd-webui-EasyPhoto#395]
由于我用的是A卡，不支持模型训练，所以用阿里云的DSW训练了一个模型，我想把它弄到本地来推理，请问我需要下载哪些文件？

**Comment by wuziheng** [comment]
参考这个 wiki，历史issue 也很多
https://github.com/aigc-apps/sd-webui-EasyPhoto/wiki/FAQ#10--%E8%AE%AD%E7%BB%83%E5%AE%8C%E7%9A%84lora-%E5%92%8C%E4%BD%BF%E7%94%A8%E5%8F%AF%E4%B8%8D%E5%8F%AF%E4%BB%A5%E6%95%B4%E4%BD%93%E5%B9%B3%E7%A7%BB

**Comment by wuziheng** [comment]
A卡的话我不确认你的链路里面其他的模型是否都可以正常运行啊，比如换脸的那个gan
