### ISSUE TITLE
预处理完到训练的时候会卡住

### ISSUE THREAD

**Issue by VideoGen** [aigc-apps/sd-webui-EasyPhoto#40]
![image](https://github.com/aigc-apps/sd-webui-EasyPhoto/assets/125348980/59abd1a0-9815-468f-a82c-b6ddb42e7b09)
请问下，我这个前面数据处理完了，但是训练的时候就卡住了，这是怎么回事啊，环境都是按照要求的去装的

**Comment by bubbliiiing** [comment]
抱歉，请问这么长时间了，进度是否有变化，这个看起来像是环境配置的问题。
这里我们推荐先手动在环境中试试accelerate是否能正常work，看起来似乎accelerate都没有反应了。
