### ISSUE TITLE
[Help]:   Template 1 error: Error info is module 'numpy' has no attribute 'int'.

### ISSUE THREAD

**Issue by Plutov23** [aigc-apps/sd-webui-EasyPhoto#400]
Template 1 error: Error info is module 'numpy' has no attribute 'int'.
`np.int` was a deprecated alias for the builtin `int`. To avoid this error in existing code, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
The aliases was originally deprecated in NumPy 1.20; for more details and guidance see the original release note at: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations.

**Comment by kuxuan128** [comment]
easyphoto使用sdwebui的解释器以及依赖包，
新版的sdwebui使用的numpy是1.26版本，numpy1.19之后没有了numpy.int
easyphoto开发时使用的应该是1.19以下的numpy所以会冲突
所以用旧版本的sdwebui应该好使，要么就把easyphoto源码中更新的地方改正

下面是机翻英语：
easyphoto use sdwebui interpreter and dependency packages, the new version of sdwebui using numpy is version 1.26, numpy 1.19 after the numpy.int easyphoto development should be 1.19 below the numpy so there will be a conflict, so with the old version of sdwebui should be good to use! So use the old version of sdwebui and it should work fine, or correct the updates in the easyphoto source code.

**Comment by wang1135562646** [comment]
所以easyphoto源码中更新的地方，做什么样的改正呢，求大佬指教

**Comment by Plutov23** [comment]
> 所以easyphoto源码中更新的地方，做什么样的改正呢，求大佬指教
> 
> So, what kind of corrections should be made to the updated parts in the easyphoto source code? Please seek guidance from the experts

其实按照上面的说法，我在秋叶的启动器那里把版本内核更换到1.6就可以解决问题了

**Comment by Plutov23** [comment]
> easyphoto使用sdwebui的解释器以及依赖包， 新版的sdwebui使用的numpy是1.26版本，numpy1.19之后没有了numpy.int easyphoto开发时使用的应该是1.19以下的numpy所以会冲突 所以用旧版本的sdwebui应该好使，要么就把easyphoto源码中更新的地方改正
> 
> 下面是机翻英语： easyphoto use sdwebui interpreter and dependency packages, the new version of sdwebui using numpy is version 1.26, numpy 1.19 after the numpy.int easyphoto development should be 1.19 below the numpy so there will be a conflict, so with the old version of sdwebui should be good to use! So use the old version of sdwebui and it should work fine, or correct the updates in the easyphoto source code.

感谢大佬

**Comment by hkunzhe** [comment]
Fixed by #397. Please upgrade to the latest version.
