### ISSUE TITLE
人脸大小判断的逻辑存在问题

### ISSUE THREAD

**Issue by hkunzhe** [aigc-apps/sd-webui-EasyPhoto#48]
### 如何复现
下载[这张照片](https://www.pexels.com/zh-cn/photo/1416736/)并上传训练，会出现下面的错误（由于加了 debug 代码，line 信息可能不一致）：
![image](https://github.com/aigc-apps/sd-webui-EasyPhoto/assets/30763967/72af1af1-1916-4428-a295-6198028ecbd3)
这是因为原图的分辨率为 `(7360, 4912)`，然而人脸的大小为 `(588.5, 750.5)`。因此，[这一行](https://github.com/aigc-apps/sd-webui-EasyPhoto/blob/main/scripts/preprocess.py#L87)会跳过导致 `face_id_scores` 为空。

**Comment by wuziheng** [comment]
谢谢你贡献的代码，我们会在今天之内参与到这个PR的review中！
