### ISSUE TITLE
training model at 40s/it ~ 17 hour for training - normal or wrong?

### ISSUE THREAD

**Issue by loertuiok065** [aigc-apps/sd-webui-EasyPhoto#51]
RTX 2080 Super Max 
8gb VRAM
32GB ram
CUDA

I have 5 pictures cropped to 512 to minimize the size.

At the moment its working at 50s/it which total 16h h for first Train.

Is this to be expected or is there something failing?

Training model at stock settings with 400it per image. Was expecting faster but since it new it might be big change given it turns out good.

Thanks.

**Comment by wuziheng** [comment]
Thats not right， according to some friends on Github， it takes less then 12mins on 4090 GPU. With my own A10， it takes，16mins。

**Comment by wuziheng** [comment]
We will make an effort to provide the community with trial plans similar to the Hugging Face demo in the near future. Please stay tuned for updates.
