### ISSUE TITLE
最后一步，存储lora保存失败

### ISSUE THREAD

**Issue by capoz1o** [aigc-apps/sd-webui-EasyPhoto#54]
saving checkpoint: outputs\easyphoto-user-id-infos\ruoruo-test2\user_weights\pytorch_lora_weights.safetensors
loading u-net: <All keys matched successfully>
loading vae: <All keys matched successfully>
loading text encoder: <All keys matched successfully>
You have disabled the safety checker for <class 'diffusers.pipelines.stable_diffusion.pipeline_stable_diffusion_inpaint.StableDiffusionInpaintPipeline'> by passing `safety_checker=None`. Ensure that you abide to the conditions of the Stable Diffusion license and do not expose unfiltered results in services or applications open to the public. Both the diffusers team and Hugging Face strongly recommend to keep the safety filter enabled in all public facing circumstances, disabling it only for use-cases that involve analyzing network behavior or auditing its results. For more information, please have a look at https://github.com/huggingface/diffusers/pull/254 .
You have loaded a UNet with 4 input channels which.
{'lower_order_final', 'dynamic_thresholding_ratio', 'solver_order', 'variance_type', 'solver_type', 'lambda_min_clipped', 'algorithm_type', 'timestep_spacing', 'sample_max_value', 'prediction_type', 'thresholding', 'use_karras_sigmas'} was not found in config. Values will be initialized to default values.
Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}}
Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}}
find model: D:\Desktop\SD\sd-webui-aki-v4.2\extensions\sd-webui-EasyPhoto-main\models\buffalo_l\2d106det.onnx landmark_2d_106 ['None', 3, 192, 192] 0.0 1.0
Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}}
find model: D:\Desktop\SD\sd-webui-aki-v4.2\extensions\sd-webui-EasyPhoto-main\models\buffalo_l\det_10g.onnx detection [1, 3, '?', '?'] 127.5 128.0
Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}}
find model: D:\Desktop\SD\sd-webui-aki-v4.2\extensions\sd-webui-EasyPhoto-main\models\buffalo_l\w600k_r50.onnx recognition ['None', 3, 112, 112] 127.5 127.5
set det-size: (640, 640)
┌───────────────────── Traceback (most recent call last) ─────────────────────┐
│ D:\Desktop\SD\sd-webui-aki-v4.2\extensions\sd-webui-EasyPhoto-main\scripts\ │
│ train_kohya\train_lora.py:1416 in <module>                                  │
│                                                                             │
│   1413                                                                      │
│   1414                                                                      │
│   1415 if __name__ == "__main__":                                           │
│ > 1416 │   main()                                                           │
│   1417                                                                      │
│                                                                             │
│ D:\Desktop\SD\sd-webui-aki-v4.2\extensions\sd-webui-EasyPhoto-main\scripts\ │
│ train_kohya\train_lora.py:1394 in main                                      │
│                                                                             │
│   1391 │   │   if args.merge_best_lora_based_face_id:                       │
│   1392 │   │   │   pivot_dir = os.path.join(args.train_data_dir, 'train')   │
│   1393 │   │   │   merge_best_lora_name = args.train_data_dir.split("/")[-1 │
│ > 1394 │   │   │   t_result_list, tlist, scores = eval_jpg_with_faceid(pivo │
│   1395 │   │   │                                                            │
│   1396 │   │   │   for index, line in enumerate(zip(tlist, scores)):        │
│   1397 │   │   │   │   print(f"Top-{str(index)}: {str(line)}")              │
│                                                                             │
│ D:\Desktop\SD\sd-webui-aki-v4.2\extensions\sd-webui-EasyPhoto-main\scripts\ │
│ train_kohya\train_lora.py:334 in eval_jpg_with_faceid                       │
│                                                                             │
│    331 │   embedding_list = []                                              │
│    332 │   for img in face_image_list:                                      │
│    333 │   │   image = Image.open(img)                                      │
│ >  334 │   │   embedding = face_recognition.get(np.array(image), face_analy │
│    335 │   │   embedding = np.array([embedding / np.linalg.norm(embedding,  │
│    336 │   │   embedding_list.append(embedding)                             │
│    337 │   embedding_array = np.vstack(embedding_list)                      │
└─────────────────────────────────────────────────────────────────────────────┘
IndexError: list index out of range
提示：Python 运行时抛出了一个异常。请检查疑难解答页面。
┌───────────────────── Traceback (most recent call last) ─────────────────────┐
│ D:\Desktop\SD\sd-webui-aki-v4.2\python\lib\runpy.py:196 in                  │
│ _run_module_as_main                                                         │
│                                                                             │
│   193 │   main_globals = sys.modules["__main__"].__dict__                   │
│   194 │   if alter_argv:                                                    │
│   195 │   │   sys.argv[0] = mod_spec.origin                                 │
│ > 196 │   return _run_code(code, main_globals, None,                        │
│   197 │   │   │   │   │    "__main__", mod_spec)                            │
│   198                                                                       │
│   199 def run_module(mod_name, init_globals=None,                           │
│                                                                             │
│ D:\Desktop\SD\sd-webui-aki-v4.2\python\lib\runpy.py:86 in _run_code         │
│                                                                             │
│    83 │   │   │   │   │      __loader__ = loader,                           │
│    84 │   │   │   │   │      __package__ = pkg_name,                        │
│    85 │   │   │   │   │      __spec__ = mod_spec)                           │
│ >  86 │   exec(code, run_globals)                                           │
│    87 │   return run_globals                                                │
│    88                                                                       │
│    89 def _run_module_code(code, init_globals=None,                         │
│                                                                             │
│ D:\Desktop\SD\sd-webui-aki-v4.2\python\lib\site-packages\accelerate\command │
│ s\launch.py:933 in <module>                                                 │
│                                                                             │
│   930                                                                       │
│   931                                                                       │
│   932 if __name__ == "__main__":                                            │
│ > 933 │   main()                                                            │
│   934                                                                       │
│                                                                             │
│ D:\Desktop\SD\sd-webui-aki-v4.2\python\lib\site-packages\accelerate\command │
│ s\launch.py:929 in main                                                     │
│                                                                             │
│   926 def main():                                                           │
│   927 │   parser = launch_command_parser()                                  │
│   928 │   args = parser.parse_args()                                        │
│ > 929 │   launch_command(args)                                              │
│   930                                                                       │
│   931                                                                       │
│   932 if __name__ == "__main__":                                            │
│                                                                             │
│ D:\Desktop\SD\sd-webui-aki-v4.2\python\lib\site-packages\accelerate\command │
│ s\launch.py:923 in launch_command                                           │
│                                                                             │
│   920 │   elif defaults is not None and defaults.compute_environment == Com │
│   921 │   │   sagemaker_launcher(defaults, args)                            │
│   922 │   else:                                                             │
│ > 923 │   │   simple_launcher(args)                                         │
│   924                                                                       │
│   925                                                                       │
│   926 def main():                                                           │
│                                                                             │
│ D:\Desktop\SD\sd-webui-aki-v4.2\python\lib\site-packages\accelerate\command │
│ s\launch.py:579 in simple_launcher                                          │
│                                                                             │
│   576 │   process.wait()                                                    │
│   577 │   if process.returncode != 0:                                       │
│   578 │   │   if not args.quiet:                                            │
│ > 579 │   │   │   raise subprocess.CalledProcessError(returncode=process.re │
│   580 │   │   else:                                                         │
│   581 │   │   │   sys.exit(1)                                               │
│   582                                                                       │
└─────────────────────────────────────────────────────────────────────────────┘
CalledProcessError: Command 
提示：Python 运行时抛出了一个异常。请检查疑难解答页面。
'['D:\\Desktop\\SD\\sd-webui-aki-v4.2\\python\\python.exe', 
'D:\\Desktop\\SD\\sd-webui-aki-v4.2\\extensions\\sd-webui-EasyPhoto-main\\scrip
ts\\train_kohya/train_lora.py', 
'--pretrained_model_name_or_path=extensions\\sd-webui-EasyPhoto-main\\models\\s
table-diffusion-v1-5', 
'--pretrained_model_ckpt=models\\Stable-diffusion\\sd-v1-5.ckpt', 
'--train_data_dir=outputs\\easyphoto-user-id-infos\\ruoruo-test2\\processed_ima
ges', '--caption_column=text', '--resolution=512', '--random_flip', 
'--train_batch_size=2', '--gradient_accumulation_steps=4', 
'--dataloader_num_workers=0', '--max_train_steps=900', 
'--checkpointing_steps=900', '--learning_rate=0.0001', 
'--lr_scheduler=constant', '--lr_warmup_steps=0', '--train_text_encoder', 
'--seed=42', '--rank=128', '--network_alpha=64', 
'--validation_prompt=easyphoto_face, easyphoto, 1person', 
'--validation_steps=900', 
'--output_dir=outputs\\easyphoto-user-id-infos\\ruoruo-test2\\user_weights', 
'--logging_dir=outputs\\easyphoto-user-id-infos\\ruoruo-test2\\user_weights', 
'--enable_xformers_memory_efficient_attention', '--mixed_precision=fp16', 
'--template_dir=extensions\\sd-webui-EasyPhoto-main\\models\\training_templates
', '--template_mask', '--merge_best_lora_based_face_id', 
'--merge_best_lora_name=ruoruo-test2', 
'--cache_log_file=D:\\Desktop\\SD\\sd-webui-aki-v4.2\\extensions\\sd-webui-Easy
Photo-main\\train_kohya_log.txt']' returned non-zero exit status 1.
Error executing the command: Command '['D:\\Desktop\\SD\\sd-webui-aki-v4.2\\python\\python.exe', '-m', 'accelerate.commands.launch', '--mixed_precision=fp16', '--main_process_port=3456', 'D:\\Desktop\\SD\\sd-webui-aki-v4.2\\extensions\\sd-webui-EasyPhoto-main\\scripts\\train_kohya/train_lora.py', '--pretrained_model_name_or_path=extensions\\sd-webui-EasyPhoto-main\\models\\stable-diffusion-v1-5', '--pretrained_model_ckpt=models\\Stable-diffusion\\sd-v1-5.ckpt', '--train_data_dir=outputs\\easyphoto-user-id-infos\\ruoruo-test2\\processed_images', '--caption_column=text', '--resolution=512', '--random_flip', '--train_batch_size=2', '--gradient_accumulation_steps=4', '--dataloader_num_workers=0', '--max_train_steps=900', '--checkpointing_steps=900', '--learning_rate=0.0001', '--lr_scheduler=constant', '--lr_warmup_steps=0', '--train_text_encoder', '--seed=42', '--rank=128', '--network_alpha=64', '--validation_prompt=easyphoto_face, easyphoto, 1person', '--validation_steps=900', '--output_dir=outputs\\easyphoto-user-id-infos\\ruoruo-test2\\user_weights', '--logging_dir=outputs\\easyphoto-user-id-infos\\ruoruo-test2\\user_weights', '--enable_xformers_memory_efficient_attention', '--mixed_precision=fp16', '--template_dir=extensions\\sd-webui-EasyPhoto-main\\models\\training_templates', '--template_mask', '--merge_best_lora_based_face_id', '--merge_best_lora_name=ruoruo-test2', '--cache_log_file=D:\\Desktop\\SD\\sd-webui-aki-v4.2\\extensions\\sd-webui-EasyPhoto-main\\train_kohya_log.txt']' returned non-zero exit status 1.

**Comment by capoz1o** [comment]
解决了，图片尺寸要完全匹配才行，我以为有bucket的概念，最后保存的时候可能没对应上。

**Comment by zhxd163** [comment]
> 解决了，图片尺寸要完全匹配才行，我以为有bucket的概念，最后保存的时候可能没对应上。

哈喽，可以加个微信沟通一下吗？

**Comment by zhxd163** [comment]
我也遇到了同样问题，我的图片大小应该一样的

**Comment by DreamPuNi** [comment]
怎么弄的呀，我也遇到这问题了
