### ISSUE TITLE
can you please upload files to hugging face or something i am not able to download from these links

### ISSUE THREAD

**Issue by clashai** [aigc-apps/sd-webui-EasyPhoto#57]
"https://pai-aigc-photog.oss-cn-hangzhou.aliyuncs.com/webui/ChilloutMix-ni-fp16.safetensors", 
        "https://pai-aigc-photog.oss-cn-hangzhou.aliyuncs.com/webui/control_v11p_sd15_openpose.pth",
        "https://pai-aigc-photog.oss-cn-hangzhou.aliyuncs.com/webui/control_v11p_sd15_canny.pth",
        "https://pai-aigc-photog.oss-cn-hangzhou.aliyuncs.com/webui/control_v11f1e_sd15_tile.pth",
        "https://pai-aigc-photog.oss-cn-hangzhou.aliyuncs.com/webui/control_sd15_random_color.pth",
        "https://pai-aigc-photog.oss-cn-hangzhou.aliyuncs.com/webui/FilmVelvia3.safetensors",
        "https://pai-aigc-photog.oss-cn-hangzhou.aliyuncs.com/webui/body_pose_model.pth",
        "https://pai-aigc-photog.oss-cn-hangzhou.aliyuncs.com/webui/facenet.pth",
        "https://pai-aigc-photog.oss-cn-hangzhou.aliyuncs.com/webui/hand_pose_model.pth",
        "https://pai-aigc-photog.oss-cn-hangzhou.aliyuncs.com/webui/vae-ft-mse-840000-ema-pruned.ckpt",
        "https://pai-aigc-photog.oss-cn-hangzhou.aliyuncs.com/webui/face_skin.pth",
        "https://pai-aigc-photog.oss-cn-hangzhou.aliyuncs.com/webui/w600k_r50.onnx",
        "https://pai-aigc-photog.oss-cn-hangzhou.aliyuncs.com/webui/2d106det.onnx",
        "https://pai-aigc-photog.oss-cn-hangzhou.aliyuncs.com/webui/det_10g.onnx",
        "https://pai-aigc-photog.oss-cn-hangzhou.aliyuncs.com/webui/1.jpg",
        "https://pai-aigc-photog.oss-cn-hangzhou.aliyuncs.com/webui/2.jpg",
        "https://pai-aigc-photog.oss-cn-hangzhou.aliyuncs.com/webui/3.jpg",
        "https://pai-aigc-photog.oss-cn-hangzhou.aliyuncs.com/webui/4.jpg",

**Comment by bubbliiiing** [comment]
May I ask if the speed is relatively slow or completely unable to download?

**Comment by irfantogluk** [comment]
> May I ask if the speed is relatively slow or completely unable to download?

Connecting getting lost most of time. Download speed 250 kbps. It took 2 days to download 850 mb model. Most of time server refused the connection. I finally downloaded after 15-20 try that 850mb model file.

**Comment by wuziheng** [comment]
OK, we got it, and we will finish this problem as soon as possible

**Comment by bubbliiiing** [comment]
I'm very sorry for the delay. We have already uploaded the weights to Hugging Face. Please check and confirm. Thank you. If you wish to automatically download, you can replace line 56 in the file easyphoto_utils.py located in the directory stable-diffusion-webui/extensions/easyphoto-sd-webui/scripts.

```python

urls        = [
    "https://huggingface.co/alibaba-pai/pai-easyphoto/resolve/main/ChilloutMix-ni-fp16.safetensors", 
    "https://huggingface.co/alibaba-pai/pai-easyphoto/resolve/main/control_v11p_sd15_openpose.pth",
    "https://huggingface.co/alibaba-pai/pai-easyphoto/resolve/main/control_v11p_sd15_canny.pth",
    "https://huggingface.co/alibaba-pai/pai-easyphoto/resolve/main/control_v11f1e_sd15_tile.pth",
    "https://huggingface.co/alibaba-pai/pai-easyphoto/resolve/main/control_sd15_random_color.pth",
    "https://huggingface.co/alibaba-pai/pai-easyphoto/resolve/main/FilmVelvia3.safetensors",
    "https://huggingface.co/alibaba-pai/pai-easyphoto/resolve/main/body_pose_model.pth",
    "https://huggingface.co/alibaba-pai/pai-easyphoto/resolve/main/facenet.pth",
    "https://huggingface.co/alibaba-pai/pai-easyphoto/resolve/main/hand_pose_model.pth",
    "https://huggingface.co/alibaba-pai/pai-easyphoto/resolve/main/vae-ft-mse-840000-ema-pruned.ckpt",
    "https://huggingface.co/alibaba-pai/pai-easyphoto/resolve/main/face_skin.pth",
    "https://huggingface.co/alibaba-pai/pai-easyphoto/resolve/main/w600k_r50.onnx",
    "https://huggingface.co/alibaba-pai/pai-easyphoto/resolve/main/2d106det.onnx",
    "https://huggingface.co/alibaba-pai/pai-easyphoto/resolve/main/det_10g.onnx",
    "https://huggingface.co/alibaba-pai/pai-easyphoto/resolve/main/1.jpg",
    "https://huggingface.co/alibaba-pai/pai-easyphoto/resolve/main/2.jpg",
    "https://huggingface.co/alibaba-pai/pai-easyphoto/resolve/main/3.jpg",
    "https://huggingface.co/alibaba-pai/pai-easyphoto/resolve/main/4.jpg",
]
```

**Comment by mimi168** [comment]
control_v11p_sd15_openpose fp16.safetensors
