### ISSUE TITLE
Inquiry about Methods Used in Project？

### ISSUE THREAD

**Issue by SKDDJ** [aigc-apps/sd-webui-EasyPhoto#58]
Hi there,

I came across your project and was really impressed by the results that you achieved. I'm interested in learning more about the methods that you used, specifically whether you employed any techniques from academic papers such as custom diffusion or dreambooth.

Would you be able to share which papers you referenced or any other resources that may be helpful in understanding the techniques used in your project?

Thank you so much for your time and help!

**Comment by wuziheng** [comment]
Thank you for your attention. Initially, we collaborated with the FaceChain project to produce an article about facial ID persisit Lora [arxiv](https://arxiv.org/abs/2308.14256). However, as our project continues to develop, we have new plans and goals. There may be future submissions or contributions related to this, possibly on Arxiv. Your continued attention is welcome
