### ISSUE TITLE
NameError: name 'logging' is not defined

### ISSUE THREAD

**Issue by hjh526400** [aigc-apps/sd-webui-EasyPhoto#67]
File "C:\Project\stable-diffusion-webui\extensions\sd-webui-EasyPhoto\scripts\easyphoto_train.py", line 226, in process_rotate_image
logging.info(f'Check rotate failed: has not exif. Return original img.')
NameError: name 'logging' is not defined

You guys forgot to import logging in easyphoto_train.py

**Comment by wuziheng** [comment]
A fresh bug import by PR64 and fixed by PR68, now closed

**Comment by ASAav123** [comment]
> A fresh bug import by PR64 and fixed by PR68, now closed
