### ISSUE TITLE
可以有推理部分的API吗

### ISSUE THREAD

**Issue by scorpioliu** [aigc-apps/sd-webui-EasyPhoto#73]
或者支持批量上传自定义图片推理

**Comment by yunkchen** [comment]
SaaS产品在走上线流程，可以加dingding群：38250008552

**Comment by wuziheng** [comment]
推理API 和 批量推理功能已经在WIKI 更新

https://github.com/aigc-apps/sd-webui-EasyPhoto/wiki/%E8%BF%9B%E9%98%B6%E6%96%87%E6%A1%A3%E2%80%90Fast-API%E8%B0%83%E7%94%A8
