### ISSUE TITLE
httpx - HTTP Request: POST http://192.168.xxx/api/predict "HTTP/1.1 200 OK"

### ISSUE THREAD

**Issue by yuanLeeta** [aigc-apps/sd-webui-EasyPhoto#82]
httpx - HTTP Request: POST http://192.168.xxx/api/predict "HTTP/1.1 200 OK"这个监测怎么去掉

**Comment by bubbliiiing** [comment]
该请求用于监控训练并前端展示。
需要到stable-diffusion-webui/extensions/easyphoto-sd-webui/scripts/easyphoto_train.py中，到215行删除如下两行即可
with block:
    block.load(refresh_display, None, logs_out, every=1)

**Comment by bubbliiiing** [comment]
> > 该请求用于监控训练并前端展示。 需要到stable-diffusion-webui/extensions/easyphoto-sd-webui/scripts/easyphoto_train.py中，到215行删除如下两行即可 with block: block.load(refresh_display, None, logs_out, every=1)
> 
> a marginal typo. 应该是 easyphoto_ui.py 这个文件里面。 😁

Yes, my fault. 3q.

**Comment by wuziheng** [comment]
已解决。可以手动关闭这个打印和监控。

**Comment by MultiChen** [comment]
> 已解决。可以手动关闭这个打印和监控。

请问在哪里可以手动关闭
