### ISSUE TITLE
如何加载SD-VAE模型

### ISSUE THREAD

**Issue by MHX1203** [aigc-apps/sd-webui-EasyPhoto#88]
请问我的stable-diffusion webui界面中，为什么没有SD-VAE的模型选项呢

![image](https://github.com/aigc-apps/sd-webui-EasyPhoto/assets/30517250/76dde63b-163d-4767-9eba-ce00fca92bc0)

是缺少了某个插件还是缺了某个设置呢

**Comment by bubbliiiing** [comment]
不好意思，这个是不是sd webui的问题呀？请问是什么情况下发生的呢？

**Comment by wuziheng** [comment]
当前最新版本已引入检验，如果没有VAE 会提示，可以使用官方提供的镜像，进行测试。
