### ISSUE TITLE
OSError：No space left on device:

### ISSUE THREAD

**Issue by DevelopmentZheng** [aigc-apps/sd-webui-EasyPhoto#90]
在硬盘还有很多的情况下，出现这个错误
通过df -h 
如下
![截屏2023-09-15 下午10 19 46](https://github.com/aigc-apps/sd-webui-EasyPhoto/assets/58904975/65383bc8-614a-47ce-94fa-c8d8c4949480)
 /dev/shm 如果满了，就会出现这个错误
可以查看下面的链接
 https://stackoverflow.com/questions/6998083/python-causing-ioerror-errno-28-no-space-left-on-device-results-32766-h
或者看AI解答

/dev/shm是一个临时的基于内存的文件系统,它利用系统的内存来保存进程间共享的数据。

通常情况下,/dev/shm目录下存储着以下几类数据:

共享内存段(Shared memory segments)
不同进程间可以使用shmget()等API来分配一块共享内存,用于进程间高速数据交换,这些共享内存段会以文件形式存在于/dev/shm目录下。

信号灯(Semaphores)
用于进程同步的信号灯也是存放在/dev/shm目录下的文件。

套接字(Sockets)
有些进程之间基于套接字通信的话, socket文件也会出现在/dev/shm下。

临时文件
一些应用程序也会利用/dev/shm来保存临时文件,相比硬盘文件系统,shm的文件IO速度更快。

其它临时数据
程序运行时的一些临时数据也可能写入到/dev/shm中。

所以简单来说,/dev/shm中主要保存的是进程间共享内存和同步所需的临时数据,它可以利用内存提高访问速度。但数据不会持久化,进程结束即丢失。

通过监控shm的使用情况,可以对系统中进程间通信方式和效率有更多了解。

**Comment by bubbliiiing** [comment]
Get.

**Comment by wuziheng** [comment]
@DevelopmentZheng  @bubbliiiing 请继续track这个issue，并试图解决，如解决，我们会尽快关闭。

**Comment by DevelopmentZheng** [comment]
ok 已经解决
