### ISSUE TITLE
为什么安装好了总是用cpu训练，使用webui推理都是用的gpu

### ISSUE THREAD

**Issue by 2016geek** [aigc-apps/sd-webui-EasyPhoto#91]
![图片](https://github.com/aigc-apps/sd-webui-EasyPhoto/assets/20659607/2248789d-1684-4102-8ccc-7b223eb38df2)
I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.

**Comment by bubbliiiing** [comment]
We just use the tensorflow-cpu library for some functionality, and pytorch-gpu for training.
