### ISSUE TITLE
[support base model load] The base checkpoint you use in Inference won't load subdictionaries.

### ISSUE THREAD

**Issue by aetherwu** [aigc-apps/sd-webui-EasyPhoto#96]

**Comment by yunkchen** [comment]
Could you check base checkpoint is fragmentary?
Show more detail log is better.

**Comment by bubbliiiing** [comment]
u mean your model in models/stable-diffusion/your_dir ?

**Comment by bubbliiiing** [comment]
Yes, I know, Support soon.

**Comment by wuziheng** [comment]
@aetherwu  新版本已支持用户在推理界面选择放在sdwebui中的基础模型，请查收。
