### ISSUE TITLE
[fixed,A10实测9分钟]整个训练过程太慢了，预处理图片剪裁打包都要10分钟，4070 12G，20张图

### ISSUE THREAD

**Issue by waaaok** [aigc-apps/sd-webui-EasyPhoto#99]
![image](https://github.com/aigc-apps/sd-webui-EasyPhoto/assets/144203874/8b16438a-3cb2-4f6c-9182-56e3209dd833)
![image](https://github.com/aigc-apps/sd-webui-EasyPhoto/assets/144203874/077836d6-7e9e-489c-a0e9-2bb5c346f1fa)

**Comment by waaaok** [comment]
![da69185ef4df57cd6c2e43344b83eb1](https://github.com/aigc-apps/sd-webui-EasyPhoto/assets/144203874/ec02151f-e79c-41b4-bfd4-841d1a143505)
已经卸载掉了 onnxruntime 安装了onnxuntime-gpu

**Comment by bubbliiiing** [comment]
你现在画面的时间并不在预处理，可以录屏或者发完整日志会更好。

**Comment by wuziheng** [comment]
@waaaok  当前问题是否已经解决，230927最新版本，A10训练需要10分钟，预处理大约3分钟左右，希望能持续就这一问题继续沟通。
